### ISSUE TITLE
Make generation of png data urls and fallback css optional

### ISSUE THREAD

**Issue by psyrendust** [filamentgroup/grunticon#109]
If you happen to be targeting ES5 compliant browsers you only need to generate the CSS that contains the svg data urls. It would be great to be able to optionally disable the output of the other 2 formats if you only want to target newer browsers.

**Comment by dcalhoun** [comment]
@jefflembeck is this still an appropriate solution? I'd like to utilize Grunticon 2.0's SVG embedding ability, but I do not want to generate any of the PNG images or fallback CSS. This doesn't seem possible currently.

**Comment by jefflembeck** [comment]
@dcalhoun so, we have an api for the loader fragment that leaves you with a potential option

If you use our grunticon loader code:
here is the embedding code  - https://github.com/filamentgroup/grunticon/blob/master/tasks/grunticon/static/grunticon.embed.js#L76

You'll see that it references `grunticon` twice in it: `grunticon.method` and `grunticon.href`. If you set those appropriately (to `"svg"` and whatever the url is for your svg data file) before you call `grunticon.svgLoadedCallback`, that should do the trick for you.

**Comment by psyrendust** [comment]
@dcalhoun I actually made a plugin to resolve my original issue. You can find it on npm: https://www.npmjs.com/package/grunt-svg-css

**Comment by dcalhoun** [comment]
@jefflembeck if I'm following you correctly, then you are directing me to:

1. Generate the SVG data CSS using [DirectoryEncoder](https://github.com/filamentgroup/directory-encoder) or @psyrendust's [grunt-svg-css](https://www.npmjs.com/package/grunt-svg-css)
2. Include Grunticon's loader script
3. Load the single CSS file generated via a standard link tag
4. Call `grunticon.ready` directly

##### Example:
```html
<script>/* [grunticon-loader] */</script>
<link href="/path/to/icons.data.svg.css" type="text/css" />
```

```javascript
grunticon.method = "svg";
grunticon.href = "/path/to/icons.data.svg.css";
grunticon.ready(function() {
  grunticon.embedIcons(grunticon.getIcons(grunticon.getCSS(grunticon.href)));
});
```

This seems to work, but is a lot. Do you still feel this is a better solution than allowing an option to disable PNG/fallback generation/loading?

**Comment by jefflembeck** [comment]
It's not a great solution, but it is a workaround that can use the tools that we've built. This ticket is not within the scope of the Grunt

**Comment by dcalhoun** [comment]
Fair enough. Thank you for the help. Great job on the building the plugin.

**Comment by pauldraper** [comment]
@jefflembeck 

> This is closed because it would skirt the entire point of grunticon as a tool. DirectoryEncoder will handle this for you.

I don't think it will. I don't see a way to generate icons with various colors, for instance.

```js
        grunticon: {
            lucidIcns: {
                files: [{
                    expand: true,
                    cwd: 'app/webroot/css/css-common/icns/min',
                    src: ['*.svg'],
                    dest: 'app/webroot/css/css-common/icns/dest',
                }],
                options: {
                    height: 72,
                    width: 72,
                    cssprefix: '.icn-',
                    template: 'app/webroot/css/css-common/icns/template.hbs',
                    datasvgcss: '_icns-data-svg.less',
                    colors: {
                        disabled: '#929292',
                        inverse: '#ffffff',
                        green: '#8DC63F',
                        blue: '#29aae1',
                        primaryGray: '#828282',
                        bluishGray: '#77818d',
                        gray: '#5a5a5a',
                        backgroundGray: '#ebebeb',
                        priorityRed: '#ed6058',
                        optionBarGray: '#444444',
                        alertYellow: '#ffaf46',
                        lightGray: '#a0a0a0',
                        mintGreen: '#92d1a6'
                    }
                }
            }
        },
```
