### ISSUE TITLE
Change background-image on CSS media query breakpoint

### ISSUE THREAD

**Issue by collagraph** [filamentgroup/grunticon#112]
As the background images are based on class names, it is difficult to change background images of icons based on CSS media query breakpoints. It can be done through javascript by reapplying CSS classes, but this can get quite messy if there are a lot of icons.

For example, social media icons displayed in green on a white background on wide screens may display on a green background on smaller screens, requiring the icons to be coloured white.

Anyone have any ideas about this? It is also possible to write media query declarations into the Grunticon generated CSS files, but again this becomes time consuming (3 CSS files, multiple icons) and changes are overwritten every time Grunt runs.

**Comment by scottjehl** [comment]
Grunticon 2.0 is out and it gives you CSS control over icons by embedding SVG markup directly into the page when a particular attribute is present. This should address your issue and more, so I'm going to close this out, but please let us know if there are outstanding reasons to reopen. Thanks!

https://github.com/filamentgroup/grunticon#version-20-is-out---heres-whats-new
