### ISSUE TITLE
PNG Fallback performance (HTTP requests)

### ISSUE THREAD

**Issue by tgdev** [filamentgroup/grunticon#119]
Does having each icon as a separate png impact site performance due to multiple http requests rather than 1 http request for a single spritesheet?

If so, is it worth having an option to generate a spritesheet from available pngs...or disable the fallback option and use another grunt sprite package that would do this?

**Comment by jefflembeck** [comment]
Ok, I'm going to close this as the enhancement is on directory-encoder, but it's on the general roadmap
