### ISSUE TITLE
Add Illustrator (.ai) export into individual .svg files

### ISSUE THREAD

**Issue by Quader** [filamentgroup/grunticon#131]
While creating svg's with Illustrator the best solution is to export them in a batched/scripted manner (js supported though). grunticon could do the job for us and all it takes is a single .ai file with all icons in it. That would be a huge simplification of the whole icon generation process in general.
 
[See Docs](http://www.adobe.com/devnet/illustrator/scripting.html)

So all it takes is to iterate through every ```pathItem``` inside the .ai document structure and export them into individual files with ```doc.exportFile(dest,type,exportOptions);```

**Comment by jefflembeck** [comment]
Deciding to close this one - exporting from .ai to svg is part of the workflow
