### ISSUE TITLE
Icons in IE8, possible to generate PNG files in different sizes?

### ISSUE THREAD

**Issue by eoto88** [filamentgroup/grunticon#132]
Changing the size of the icons is easy with "background-size: cover;" but sadly it's not working with IE8 and under. So what would be the best way to make icons scalable with IE8 and under? Generate PNG files in different sizes or use "filter" and "-ms-filter"?

I already use "file.colors-c1-c2-c3.svg" to generate icons in different colors so would it be possible to generate icons in different sizes using "file.colors-c1-c2-c3.sizes-s1-s2.svg"? Personnaly, I don't mind to make more HTTP requests with IE8 and under, at least the icons would appears in the right size. Also it would be possible to make a sprite image per icon size to reduce HTTP requests.

**Comment by jefflembeck** [comment]
I see the utility in this - I really do.

But, I think I'm going to avoid putting this functionality in. It's pretty complex and serves a use-case that is limited.

That being said, with a little interesting hacking, and some sass, one could output their css files to different sass files, then use a mixin that only applies to the fallback icon that puts in an ms-filter and filter solution to make background-size: cover work

I strongly suggest that route if you're going to do this.
