### ISSUE TITLE
two files with the same name cause error even after they are removed from input dir

### ISSUE THREAD

**Issue by chrisheinzelmann** [filamentgroup/grunticon#162]
I had two files with the same name in my input directory (foo.svg & foo.png) and I got the following error:
Fatal error: Two files with the same name: `foo` exist in the input directory
I removed both from the input directory but the error was thrown again.
I deleted the destination directories, changed the input directory name - this didn't help.

I finally resolved it by finding the node tmpDir via os.tmpDir() in terminal and deleting the grunticon folder there.

**Comment by lukewhitehouse** [comment]
I've just ran into the same issue and found that the problem was my `tmp` directory was still there and hadn't been deleted because grunticon errored and the task stopped.

It'd be cool to put some logic in place to delete the `tmp` folder on error or something. Any suggestions?

**Comment by jefflembeck** [comment]
@lukewhitehouse oh wow, we actually delete before the tasks run - I'll look into your issue

**Comment by lukewhitehouse** [comment]
@jefflembeck Let me know if you can't recreate the problem; I'll try to myself and report back.

**Comment by jefflembeck** [comment]
@lukewhitehouse I definitely cannot currently recreate.
