### ISSUE TITLE
Android 3.0 does not support svg

### ISSUE THREAD

**Issue by arschmitz** [filamentgroup/grunticon#174]
Android 3.0 does not support svg however it currently passes the support tests 
see https://github.com/jquery/jquery-mobile/issues/6711
and https://github.com/jquery/jquery-mobile/pull/7258/ for a potential fix

**Comment by jefflembeck** [comment]
We have no way to test this so we're going to close on the whim that it's so underused that we can't find a way to support it. Just going to close as a WONTFIX

**Comment by arschmitz** [comment]
Yeah we dropped support for android 3.0 anyway

**Comment by jefflembeck** [comment]
@arschmitz yeah, that's what prompted the close.
