### ISSUE TITLE
Add a way to prepend custom css to generated CSS files

### ISSUE THREAD

**Issue by mstorus** [filamentgroup/grunticon#179]
I'd like to have a way to add custom CSS to the beginning of the generated PNG, SVG, or fallback files.

The existing `options.template` seems to only allow me to set the template for each source image.

Not sure if this feature would belong in DirectoryEncoder or Grunticon.

**Comment by jefflembeck** [comment]
Ok, I've given this thought and this is something you can handle with https://github.com/gruntjs/grunt-contrib-concat in a far nicer fashion than anything we might come up with.
