### ISSUE TITLE
Feature request: options.urlsvgcss

### ISSUE THREAD

**Issue by thisischrisj** [filamentgroup/grunticon#185]
It would be good to introduce a urlsvgcss option which outputs all the SVG backgrounds but as paths to the source files rather than as data URIs (similar to the urlpngcss option for IE8).

This sounds counter intuitive but consider the scenario where grunticon runs on a 150 page site each containing one unique grunticon icon. The datasvgcss file contains the datauri for all 150 icons even though only one is needed. That file would also be very large.

With a file that generates SVG urls only the single SVG is downloaded. It adds an extra request and you'd loose the benefit of concatenation but in this particular scenario the reduced download size is the greater good.

I'm sure there's other ways of achieving the same thing but it'd be good to have this built into the existing plug-in.

**Comment by jefflembeck** [comment]
Ok, closing this here to open over here - https://github.com/filamentgroup/directory-encoder/issues/20
