### ISSUE TITLE
Automatically determine color variations based on usage

### ISSUE THREAD

**Issue by dkeeghan** [filamentgroup/grunticon#186]
As an enhancement request I would love to see the ability to not worry about naming the files with the appropriate colours e.g. `file.colors-primary-secondary.svg` but instead just use `file.svg` and grunticon will look at the selectors specified and generate the appropriate output.

This will allow for simplification of a few scenarios:

* Keeping naming of artboards in AI aligned (we constantly find that we change the SVG name, but not the artboard)
* Allow for quick prototyping of new colours/simpler process of adding new coloured icons
* If you have a situation where there are a large number of white icons, you could save all the icons out as black icons instead, then use `-white` in the stylesheet without adding significant overhead because the black icons aren't used in the stylesheet, thus aren't exported.

@plummer came up with a rough solution for our latest project which compares the final '-XXX' in each selector list and compare the value with the list of colours specified in the colours variable. If the colour doesn't exist, it's assumed that it doesn't have a colour and to just use the base colour.

*Downsides:*
You won't be able to name your files with a colour as the last word in the filename.

**Comment by jefflembeck** [comment]
We're going to work on a different way to approach this problem - continuing this over here - https://github.com/filamentgroup/directory-colorfy/issues/13
