### ISSUE TITLE
Make prefixClass available to template

### ISSUE THREAD

**Issue by mjswensen** [filamentgroup/grunticon#187]
Currently the template variable `prefixClass` is available to the preview template. It would be nice if the variable could be available to the CSS output template as well.

For example, when using a tool like [styledocco](http://jacobrask.github.io/styledocco/) that generates documentation from comments in stylesheets, a template file might look like this:

    /*

    {{prefix}}{{name}}:

    ```
    <span class="{{prefixClass}}{{name}}"></span>
    ```

     */
    {{#each customselectors}}{{this}},{{/each}}
    {{prefix}}{{name}} {
      background-image: url('{{datauri}}');
      background-repeat: no-repeat;
    }

**Comment by jefflembeck** [comment]
Moved to https://github.com/filamentgroup/directory-encoder/issues/19
