### ISSUE TITLE
Can we have different icons with the same class name but different class prefix?

### ISSUE THREAD

**Issue by hustcer** [filamentgroup/grunticon#192]
Hello,

Can we have different icons with the same class name but different class prefix? Something like this:
```css
.item{...}
.selected .item{...}
.visited .item{...}
```
They have the same class name, but might be of different colors. 
or we have to use:
```css
.item{...}
.item-selected{...}
.item-visited {...}
```
This is very important, because It's more convenient to toggle parent class name than change each icon class name.
Thanks.

**Comment by jefflembeck** [comment]
I'm actually going to close this one since it can be handled pretty simply with our custom selectors and that's mostly what they're here for.

example:

```JavaScript
customselectors: {
  "item-selected" : [".selected .item"],
  "item-visited" : [".visited .item"]
},
```

**Comment by hustcer** [comment]
Thanks, I will try this later!
