### ISSUE TITLE
DynamicColorOnly option - not working

### ISSUE THREAD

**Issue by steve-king** [filamentgroup/grunticon#195]
Hey, thanks for such a great plugin. Auto generating coloured icons is an excellent feature. I'm trying out this feature to ignore the colour contained in the SVG, but it's not working for me (v1.3.0).

In my options, I have:

```
dynamicColorOnly : true,
    colors : {
    black : "#2e2e33",
    white : "#fff"
}
```

I'm naming my icon files as `twitter.colors-black-white.svg`, and getting the following:

```
twitter-black.png
twitter-white.png
twitter.png
```

Am I doing something wrong?

**Comment by davidpauljunior** [comment]
This may be a silly question, but how do I install this latest version via npm?  I tried npm install grunt-grunticon@1.5.2 --save but it didn't seem do anything.

**Comment by jefflembeck** [comment]
Maybe worth retrying, I just attempted `npm install grunt-grunticon@1.5.2` and was successful

**Comment by davidpauljunior** [comment]
Thanks @jefflembeck, I got confused because when I put npm grunt-grunticon -v it shows 1.4.14, which I'm now presuming is the latest 'release' available.  But if I type npm list then it shows grunt-grunticon as 1.5.2.
