### ISSUE TITLE
Milestone 2.0 Summary

### ISSUE THREAD

**Issue by scottjehl** [filamentgroup/grunticon#203]
Open tickets: https://github.com/filamentgroup/grunticon/milestones/2.0

We've hatched a plan to add support for inline SVG without modifying anything in the Grunticon workflow aside from a small client-side JavaScript addition. Basically, we will be able to extract the SVG icons from the CSS we already request in qualified browsers, so when desirable, we can inject SVG icons directly into the page either through embedded SVG markup or possibly the use and defs elements (which could be better for performance but come with limitations as well).

The ability to use either of those inline SVG approaches will dramatically change what we're able to do with Grunticon, such as applying scripting and CSS to icons in bulk or individually. Animating and styling portions of an icon become quite simple. And best of all, the approach will build upon our existing fallback system to guarantee all browsers get an icon.

To implement this feature, we are thinking it makes sense to improve Grunticon's loader JS by exposing a small API. The existing loader script won't need to change much in file size, but exposing some small things like a callback when the SVG CSS file finishes loading will allow us to tie in optional extensions that parse that CSS and inject it into desired locations in the page (elements that have data-grunticon-embed attributes, or example.

Milestone features include:

- Inline SVG Support (for styling, animating and scripting icons)
- Improved modular loader script with extensions
- Test suite for loader script
- Improvements to re-coloring feature: https://github.com/filamentgroup/directory-colorfy/issues/10

**Comment by jefflembeck** [comment]
Launched.
