### ISSUE TITLE
svg-to-png now spawning phantomjs – Phantom Error

### ISSUE THREAD

**Issue by tracystone** [filamentgroup/grunticon#207]
I'm having an issue similar to #130, but no luck fixing it with the permissions solutions provided. Grunticon had been working fine, then without me changing any svg files (I have about 28 icons) or gruntfile.js, it stopped working. I get the following output:

```
Running "grunticon:dist" (grunticon) task
Look, it's a grunticon!
grunticon now minifying the stylesheet loader source.
grunticon loader file created.
Coloring SVG files
Converting SVG to PNG
svg-to-png now spawning phantomjs...
(using path: /Users/tracystone/Sites/project/node_modules/grunt-grunticon/node_modules/svg-to-png/node_modules/phantomjs/lib/phantom/bin/phantomjs)

Something went wrong with phantomjs...
```
Then, it outputs the following for each icon and color: `/var/folders/xf/jr0ct9wx4db6_j30brtfxv280000gn/T/grunticon-tmp/access-admin.svg`

And, at the end:
```
PHANTOM ERROR: Error: Error: fail
TRACE:
 -> /Users/tracystone/Sites/project/node_modules/grunt-grunticon/node_modules/svg-to-png/lib/phantomscript.js: 43
 -> /Users/tracystone/Sites/project/node_modules/grunt-grunticon/node_modules/svg-to-png/lib/rsvp.js: 241
 -> /Users/tracystone/Sites/project/node_modules/grunt-grunticon/node_modules/svg-to-png/lib/rsvp.js: 872
```
Any ideas?

**Comment by jefflembeck** [comment]
@tracystone 2 things:

First, which version of Grunticon?
Second, I actually, weirdly enough, know WHERE the "fail" error comes from. It happens when phantomjs cannot open the file it's being told to open. Any chance you could post up your Gruntfile and the project structure as well? (If the project is able to be public in the way that I could look at how it's set up, that would be world-changing levels of helpful as well)

**Comment by tracystone** [comment]
Thanks.

Grunticon version 1.6.0. I also tested it with 2.0.0-beta.1, but had the same issue.

I'm only able to show the portion of the Gruntfile that includes grunticon:

```
grunticon: {
      dist: {
        files: [{
          expand: true,
          cwd: 'svg/compressed',
          src: ['*.svg', '*.png'],
          dest: 'public/img/ui/icons'
        }],
        options: {
          cssprefix: '.icon--',
          colors: {
            dark: '#555555',
            primary: '#0099cc',
            tertiary: '#003366',
            quaternary: '#f9c900',
            explorer: '#004f84',
            admin: '#4a5259',
            reverse: '#ffffff',
            alert: '#E2565C',
            success: '#3CB57E',
            googlecolor: '#d03324',
            linkedincolor: '#0077b5'
          }
        }
      }
    },
```

**Comment by jefflembeck** [comment]
Hey @tracystone, just to doublecheck, can you - in the place for cwd, instead try

```JavaScript
path.resolve( path.join( 'svg', 'compressed' ) )
```

It may be unrelated, but I'd like to see if I can find an error somewhere. Meanwhile, I'll try to find a way to catch this error earlier

**Comment by tracystone** [comment]
@jefflembeck Do you mean replace `cwd: 'svg/compressed',` with `cwd: path.resolve( path.join( 'svg', 'compressed' ) )`?

**Comment by jefflembeck** [comment]
Yeah.  If you're not using `path` elsewhere in your Gruntfile, you'll need to require it at the top:  `var path = require( 'path' );`

**Comment by tracystone** [comment]
@jefflembeck Produced the same errors.

**Comment by jefflembeck** [comment]
Hey @tracystone, any chance you can try `2.0.0-beta.2`? It should have a slightly better error message.

Thanks!

**Comment by tracystone** [comment]
@jefflembeck Thanks for the better error message. I tried `2.0.0-beta.2` and it came up with the following:
```
Something went wrong with phantomjs...
PHANTOM ERROR: Error: Error: fail: Phantom had an error opening - /var/folders/xf/jr0ct9wx4db6_j30brtfxv280000gn/T/grunticon-tmp/publish-success.svg - Does it exist? true
TRACE:
 -> /Users/tracystone/Sites/sage-ui/node_modules/grunt-grunticon/node_modules/svg-to-png/lib/phantomscript.js: 43
 -> /Users/tracystone/Sites/sage-ui/node_modules/grunt-grunticon/node_modules/svg-to-png/lib/rsvp.js: 241
 -> /Users/tracystone/Sites/sage-ui/node_modules/grunt-grunticon/node_modules/svg-to-png/lib/rsvp.js: 872
```
I removed the publish.svg icon, to see if something was wrong with it. But, then it snagged on the next icon in alphabetical order. So I tried removing those icons and a few more. It appears grunticon works up to 24 icons (no matter which 24), beyond which it errors out.

I then checked the `/var/folders/…/grunticon-tmp/` directory and found that it contained all svg icons in all colors. So they do exist.

Does this mean Phantom is timing out? Or the cache is too full?

**Comment by jefflembeck** [comment]
@tracystone - so, I was able to get this working with 50 icons, so it's not necessarily a set number.

Which version of OSX are you using? Is the 24th icon different than any of the others in any specific way (really large)? Just trying to get whatever info I can get to help

**Comment by jefflembeck** [comment]
Also, how many individual icon + color combinations are there? Are there 24 all together or are there 100+?

**Comment by tracystone** [comment]
@jefflembeck OSX 10.9.5. All icons are the same size (48x48). It errors on the 25th icon no matter which one it is.

There are 10 colors per icon including the default color. (I know, trying to reduce the number of colors!)

**Comment by jefflembeck** [comment]
ok, so I just tried with 500 icons and was still able to make it work. I'm super curious as to what is happening here.

**Comment by jefflembeck** [comment]
@tracystone what type of size (in KB) are the icons that are being produced? I'm struggling to reproduce so I'm reaching for whatever I can.

**Comment by tracystone** [comment]
@jefflembeck Thanks for trying to help here. Unfortunately I haven't been able to test in the past week.

The svgs are compressed with svgmin and range from 200 bytes to 1kb.

**Comment by tracystone** [comment]
@jefflembeck We've since moved to a Vagrant virtual machine, so I don't have the icon issues anymore. It very well may have been a permissions issue. Not sure.

Thanks again for your help!

**Comment by jefflembeck** [comment]
@tracystone - glad it's working for you!

**Comment by jaiew** [comment]
I was having this issue today on version 2 of grunticon where it was saying it couldn't find the file even though it existed.

Also on a Mac.

I ended up just splitting the processing into two tasks and it worked:
```
   grunticon: {
      iconsA: {
        files: [{
          expand: true,
          cwd: 'images/icons',
          src: ['**/*_icon.svg'],
          dest: 'generated/grunticon/icons'
        }],
        options: {
          cssprefix: '.ski-icon-'
        }
      },
      iconsB: {
        files: [{
          expand: true,
          cwd: 'images/icons',
          src: ['**/*_logo.svg'],
          dest: 'generated/grunticon/icons'
        }],
        options: {
          cssprefix: '.svg-icon-'
        }
      }
    }
```

**Comment by jefflembeck** [comment]
@jaiew 
> I was having this issue today on version 2 of grunticon where it was saying it couldn't find the file even though it existed.

Can you clarify what you mean by this? Which file? What was the exact error message? What was reporting the error?

**Comment by jaiew** [comment]
@jefflembeck Originally I was processing all the logos and icons in one config as such:

```
grunticon: {
      icons: {
        files: [{
          expand: true,
          cwd: 'images/icons',
          src: ['**/*_{icon,logo}.svg'],
          dest: 'generated/grunticon/icons'
        }],
        options: {
          cssprefix: '.ski-icon-'
        }
      },
```

The process would end with the same error that @tracystone mentioned. Even when I removed the file it failed on it would just fail on the next file after that.

So I split it into two processes iconsA and iconsB.

I hope that clarifies it.

**Comment by LouAdrien** [comment]
Same problem here, exactly. It seems there is an issue with max temp files opened at the same time on macOS (10.10.3 for me).

**Comment by jefflembeck** [comment]
@LouAdrien there's most definitely a maximum amount of files that one can open at once on OSX (and unix in general)

`ulimit -n` should expose that for you
