### ISSUE TITLE
Fix preview.html

### ISSUE THREAD

**Issue by ldexterldesign** [filamentgroup/grunticon#208]
Hey,

```prefixClass``` doesn't appear to be rendering https://github.com/filamentgroup/grunticon/blob/master/example/preview.hbs#L23

Currently I have to set the following empty value to even get the preview.html file working:
```
        grunticon: {
            myIcons: {
                files: [{
                    expand: true,
                    cwd: 'img/layout',
                    src: ['*.svg', '*.png'],
                    dest: 'img/layout/grunticon'
                }],
                options: {
                  cssprefix: ""
                }
            }
        }
```

I'm probably doing something wrong, but I expected preview.html to work out of the box :hammer: 

Regards,

**Comment by jefflembeck** [comment]
Which version of grunticon are you using? Which OS? What value were you trying that's not working?

**Comment by ldexterldesign** [comment]
I don't want a prefix, so I tried an empty string ```""``` and ```" " ```

```{{prefix}}``` updated in preview.html, but ```{{prefixClass}}``` didn't, leading me to think something was/is buggy

Regards,

**Comment by jefflembeck** [comment]
@ldexterldesign with no prefix, there will just be a filename as the selector - I believe that we have the ability to do that overridden - if you're using your own class prefix on the filename, I believe "." as your prefix class is the way to go (this, of course, will not work if your filename would not be an appropriate class such as `.0001-home`)

**Comment by ldexterldesign** [comment]
@jefflembeck could you give me an example of "no prefix" because none of the following seemed to work for me:
```
        grunticon: {
            myIcons: {
                files: [{
                    expand: true,
                    cwd: 'img/layout',
                    src: ['*.svg', '*.png'],
                    dest: 'scss/vendor/grunticon'
                }],
                options: {} // add "icon-" prefix
            }
        }
```

```
        grunticon: {
            myIcons: {
                files: [{
                    expand: true,
                    cwd: 'img/layout',
                    src: ['*.svg', '*.png'],
                    dest: 'scss/vendor/grunticon'
                }],
                options: {
                    cssprefix: "" // add "icon-" prefix
                }
            }
        }
```

```
        grunticon: {
            myIcons: {
                files: [{
                    expand: true,
                    cwd: 'img/layout',
                    src: ['*.svg', '*.png'],
                    dest: 'scss/vendor/grunticon'
                }],
                options: {
                    cssprefix: "." // prefix/replace dot (".") with dot
                }
            }
        }
```

Yours hopefully,

**Comment by zolitch** [comment]
I can confirm that this is still an issue in ver 2.0.0.

I am also on OS X Yosemite.

I have replicated the same steps as @ldexterldesign. I have tried to look at fixing myself in the repo but can't find where the  `prefixClass` is assigned. So to re-iterate, it is just the preview file that is not rendering the css class correctly:

`<pre><code>.icon-burger:</code></pre><div class="burger" style="width: 32px; height: 30px;" ></div><hr/>`

should be rendering as:

`<pre><code>.icon-burger:</code></pre><div class="icon-burger" style="width: 32px; height: 30px;" ></div><hr/>`

The css itself in the .css files is fine and has the '.icon-' prefixed.

I have also tried including the https://github.com/filamentgroup/grunticon/blob/master/example/preview.hbs#L23 preview file and referencing it in my repo with:

`options: {
              previewTemplate: "source/preview-custom.hbs"
            }`
But to no avail. 

The only way to get a working preview right now is by naming every svg file as 'icon-filename.svg'  and then adding 
`options: {
              cssprefix: '.'
            }`
But this is no way forward for production so I'll be creating my own preview file for now.

**Comment by jefflembeck** [comment]
I think I've got this one working in 2.0.1 - Sorry about that, misunderstood the issue.

**Comment by zolitch** [comment]
Boom!

Nailed it. 

Thanks!

**Comment by ldexterldesign** [comment]
@jefflembeck kind thanks
