### ISSUE TITLE
Enhance to output SCSS Partials

### ISSUE THREAD

**Issue by ldexterldesign** [filamentgroup/grunticon#209]
Hey,

In addition to the CSS files (and [PNG] fallbacks) the tool generates, it would be useful to have SCSS files too, which we could use as Partials

Any plans/thoughts on this?

Yours hopefully,

**Comment by jefflembeck** [comment]
We've made a decision to forgo building SCSS files deliberately.

That being said, you are free to name output files however you'd like to name them.

```
datasvgcss: "_icons.data.svg.scss",
datapngcss: "_icons.data.png.scss",
urlpngcss: "_icons.fallback.scss",
```
for example, could be used as a set of options on a second run that will create exactly what you need.

**Comment by ldexterldesign** [comment]
Thanks - I'll look into this!

**Comment by ldexterldesign** [comment]
Works great!

Kind thanks,
