### ISSUE TITLE
Only works when inlining the loader.js?

### ISSUE THREAD

**Issue by anselmh** [filamentgroup/grunticon#211]
Hey,

thanks for releasing 2.0. However I noticed that in the README there’s only a small mention that you need to include a JavaScript [generated here](https://github.com/filamentgroup/grunticon/blob/master/tasks/grunticon/static/grunticon.loader.js)—the `grunticon.loader.js`.
Naturally I tried to include this using `<script src="" async>` tag in head which didn’t really work. No css link element is applied by the script as it should. Starting to try other options I found out that it needs to be inlined instead.

Would be great if you either make it available to use as external script, too (which I’d prefer if nothing is hindering) or if you add this to the readme.

Cheers,
Anselm

**Comment by jefflembeck** [comment]
Added a mention in the README for this, thank you!

**Comment by anselmh** [comment]
Thanks!
