### ISSUE TITLE
Callback for embedded SVG loaded?

### ISSUE THREAD

**Issue by jimlakey** [filamentgroup/grunticon#213]
Excited about grunticon 2.0, but having a bit of trouble firing a GSAP animation on embedded SVG. I can't see it in the docs, but is there a callback to use to when the SVG embed has finished and the SVG is in the DOM? 

Right now, I'm just using document ready to fire the GSAP animation on some paths in the SVG which grunticon is embedding, and sometimes it works and sometimes it doesn't depending on whether the SVG is in the DOM yet or not by the time document ready is fired.

Thanks!

**Comment by jefflembeck** [comment]
So, a pretty good way of handling this right now is in the loading of your grunticon stuff.

```
grunticon( ["icons.data.svg.css", "icons.data.png.css", "icons.fallback.css"], function(){
  grunticon.ready(function(){
    grunticon.embedIcons(grunticon.getIcons(grunticon.href));
    // FIRE YOUR EVENT HERE
  });
};
```

Should do the trick. grunticon.ready waits until domready to fire everything else

**Comment by jimlakey** [comment]
Thanks! Just a note for anyone using this code, the closing paranthesis is missing. The code should be:

```
grunticon( ["icons.data.svg.css", "icons.data.png.css", "icons.fallback.css"], function(){
  grunticon.ready(function(){
    grunticon.embedIcons(grunticon.getIcons(grunticon.href));
    // FIRE YOUR EVENT HERE
  });
});
```

**Comment by timrourke** [comment]
I know this issue has been closed, but it's worth pointing out that the correct syntax for firing a custom callback must now include an additional nested call to grunticon.getCSS():

```
grunticon(
	   ["<?php echo get_template_directory_uri(); ?>/svgs/icons.data.svg.css", 
		"<?php echo get_template_directory_uri(); ?>/svgs/icons.data.png.css", 
		"<?php echo get_template_directory_uri(); ?>/svgs/icons.fallback.css"], 
		function(){
		  grunticon.ready(function(){
		    grunticon.embedIcons(grunticon.getIcons(grunticon.getCSS(grunticon.href)));
		   // FIRE YOUR EVENT HERE
		  });
		});
```

This method became incredibly important for me to find, as my use case require animating the svg after it's been completely embedded into the document. I would suggest perhaps referencing it in the docs for dense newbs like me who wouldn't find it on their own. :D

**Comment by timrourke** [comment]
Whoops, guess you can ignore the php and overly specific paths I left in the above example.
