### ISSUE TITLE
Avoiding critical CSS inclusion 

### ISSUE THREAD

**Issue by rarkins** [filamentgroup/grunticon#215]
With this CSS data-uri approach, how can we avoid bloating critical CSS with the data URIs if icon classes are used above the fold? Ie what's the process for making this compliment the criticalCSS extraction workflow? With SVG sprites and SVG use it's not a problem.

**Comment by jefflembeck** [comment]
So, I'm looking to address this over here: https://github.com/filamentgroup/criticalCSS/issues/18 (and going to close this here) - but criticalcss should only be grabbing from the file you specify, so you should be able to leave out icons if you're not referencing them in your main css file (that you're using for critical).
