### ISSUE TITLE
Trouble installing 2.1.0

### ISSUE THREAD

**Issue by jimlakey** [filamentgroup/grunticon#224]
Not sure if this is just a system error on my end or not. Getting error `npm ERR! cb() never called!` when trying to install. I updated my package.json to use 2.1.0, ran `npm cache clean` and then `npm install`. Phantomjs installs within the `node_modules` for `directory-colorfy` but then I get the error.

I'm running:
NPM v2.4.1
Node v0.10.36
Grunt v0.4.5

I had no trouble installing grunticon 2.0.1 previously. Thanks, and apologies if this is a system error on my end rather than an issue with 2.1.0.

**Comment by jefflembeck** [comment]
Windows or osx?

**Comment by jimlakey** [comment]
osx 10.9.5

**Comment by jimlakey** [comment]
I tried reinstalling v2.0.1 and having similar issues. So pretty sure I've got some gremlins in the system here and it's unrelated to grunticon. Sorry.

**Comment by jefflembeck** [comment]
@jimlakey closing out then. Open back up if you run into this again

**Comment by jimlakey** [comment]
I rolled npm back to 1.4.28 and the errors went away and the new version of grunticon installed just fine.
