### ISSUE TITLE
svgLoadedCORSCallback error

### ISSUE THREAD

**Issue by jimlakey** [filamentgroup/grunticon#225]
With the v2.1.0, and dealing with my assets being on a CDN, the following code gets an `Uncaught TypeError: object is not a function` error:

```
grunticon.embedComplete = function() {
          TweenMax.staggerTo('.star', 1.2, {
            scale: 0.5,
            fill: "#C8BDE5",
            repeat: -1,
            yoyo: true,
            transformOrigin:"50% 50%"
          }, 0.25);
        };

grunticon( ['{{ "icons.data.svg.css" | asset_url }}', '{{ "icons.data.png.css" | asset_url }}', '{{ "icons.fallback.css" | asset_url }}'], grunticon.svgLoadedCORSCallback );
```

The error points to line 35 of grunticon/tasks/grunticon/static/grunticon.embed.cors.js with callback() not being a function. If in the minified loader.js I change callback() to grunticon.embedComplete(), it works as expected, with the animation running on the newly embedded SVG:
```
e.embedIcons(e.getIcons(r)),t&&t();
```
to
```
e.embedIcons(e.getIcons(r)),t&&grunticon.embedComplete();
```
As my question quite possibly belies, I don't have a great deal of understanding of what's going on under the hood with grunticon, but I don't see how `grunticon.embedComplete` gets added as the callback. I define it, which is what I understood from the readme, but I guess I don't get how the loader then knows to do anything with this newly defined function.

Thank you once again for all your time.

**Comment by jefflembeck** [comment]
Ah. Doc change coming. Pass an anonymous function as the second argument into grunticon and call grunticon.svgLoadedCORSCallback(yourFunction) inside of it.

**Comment by jimlakey** [comment]
Fantastic! Worked a treat. Thank you.

**Comment by jefflembeck** [comment]
Docs changed, thanks
