### ISSUE TITLE
set 'background-repeat: no-repeat;' with an attribute selecter

### ISSUE THREAD

**Issue by Jugibur** [filamentgroup/grunticon#226]
If using a lot of icons, it could be more efficient, to remove 'background-repeat: no-repeat' from each icon and declare a attribute selector to set this code, like so:

[class^="icon-"] {
 background-repeat: no-repeat
}

**Comment by jefflembeck** [comment]
@Jugibur so, you can actually use a template for this - https://github.com/filamentgroup/grunticon#optionstemplate

we keep a template here - https://github.com/filamentgroup/grunticon/blob/master/example/default-css.hbs and reference it here - https://github.com/filamentgroup/grunticon/blob/master/Gruntfile.js#L87

You can remove the `background-repeat` rule there and then add

```css
[class^="icon-"] {
  background-repeat: no-repeat
}
```

to your regular css.
