### ISSUE TITLE
Grunticon gets stuck 'Coloring SVGs' Task

### ISSUE THREAD

**Issue by hassanzaheer123** [filamentgroup/grunticon#233]
I'm converting some 90+ svg files to different colors. If the number of colors (defined using the filename notation) exceeds about two then grunticon gets stuck in 'Coloring SVGs' task for indefinitely. I've checked 'Activity Monitor' and it shows a number of phantomjs instances, all complete unresponsive. While the same files with one or two color options work fine.

Any response/alternative to this will be highly appreciated. Thanks :)

**Comment by hassanzaheer123** [comment]
@jefflembeck  can someone please look into it? Kind of stuck at something and needs to resolve it asap. Thanks :)

**Comment by zachleat** [comment]
Patience, friend. @jefflembeck does a very good job maintaining this project and comments like this do little to help with the stress of open source! Please please please keep it positive—thanks!

**Comment by jefflembeck** [comment]
Looking into this over here: https://github.com/filamentgroup/directory-colorfy/issues/15

**Comment by jefflembeck** [comment]
Should be updated and fixed in 2.1.5
