### ISSUE TITLE
'../' in grunticon path parameters does not work

### ISSUE THREAD

**Issue by duhseekoh** [filamentgroup/grunticon#234]
lets say I have my built directory in my project layed out as such:

```
assets/grunticons
--- grunticon.loader.js
--- icons.data.png.css
--- icons.data.svg.css
--- icons.fallback.css

styleguide
--- index.html
```

in index.html

```
...
<script>
   grunticon(["../assets/grunticons/icons.data.svg.css", "../assets/grunticons/icons.data.png.css", "../assets/grunticons/icons.fallback.css"]);
</script>
...
```

That would seem to work, the paths are correct. The 'link' tag is being appended to the stylesheet, but the `media = "only x"` is never being removed/replaced with 'all'. 

Looks like the grunticon loader script is sitting in an endless loop because it can never verify that the link tag for the icons sheet has been appended to the page. That check expects `../assets/grunticons/icons.data.svg.css` to be contained in the href of the link tags its looping through. That never happens because the hrefs of the link tags are fully qualified paths like `http://localhost:8080/assets/grunticons/icons.data.svg.css`. 

So at this point it doesn't seem like its possible to use `../` inside the grunticon paths.

Can you confirm that?

**Comment by jaydiablo** [comment]
Seeing the same behavior in Grunticon version 2.1.2 when using "../" in the CSS path.  The "only x" is never changed to "all".

setTimeout then consumes a fair amount of CPU on an otherwise idle page.

![screen shot 2015-03-03 at 5 30 39 pm](https://cloud.githubusercontent.com/assets/136907/6475752/091851a6-c1cb-11e4-929a-0168aaa084d9.png)

**Comment by FStop** [comment]
Same issue here.

**Comment by FStop** [comment]
I made a dirty jQuery hack to get around this until they fix it:

```
$('link[href*="grunticon"]').attr('media', 'all');
```

I'm not proud of it, but it does work.

**Comment by FStop** [comment]
Of course making sure the stylesheet is loaded first is important for the hack to work. I'm lazy and not very good at JavaScript, so I found [this little plugin](https://gist.github.com/buu700/4200601) that waits until the thing exists before doing the thing you want.

So I have this in my footer:

```
$('link[href*="grunticon"]').waitUntilExists(function() {
    $(this).attr('media', 'all');
});
```

and it works OK. Still a dirty hack, but we do what we gotta do.

**Comment by pfulton** [comment]
I think I'm having the same issue or a similar issue.

Here's what I'm doing to fix it, and it seems to be working:
(in the script loader snippet)
```
// grab the window.location.origin & and assign it to a variable
var hostOrigin = window.location.origin;
```

Then, in the requests to the grunticon CSS files, I add the hostOrigin to the beginning of the path:

`grunticon([hostOrigin + "/assets/grunticon/icons.data.svg.css", ...`

**Comment by nhall** [comment]
Checking in on this one as it continues to be an issue. If using `../` in the path parameters the media attribute of `only x` never resolves to `all`.

**Comment by dominikwilkowski** [comment]
:+1: for `only x`

**Comment by jon301** [comment]
Did you find a workaround for this issue ? 

Love this plugin btw, keep up the good work guys

**Comment by dominikwilkowski** [comment]
For right now the only way is to make the path absolute. This is how we "fixed" it anyhow...

**Comment by pstenstrm** [comment]
I did my fix to the minified js, so the examples might not be super clear.

In the loop that does the href check:

```js
for(var e,n=0;u.length>n;n++)u[n].href&&u[n].href.indexOf(t)>-1&&(e=!0);
```

I added a regex that removes any occurrence of `../`

```js
for(var e,n=0;u.length>n;n++)u[n].href&&u[n].href.indexOf(t.replace(/\.\.\//g,''))>-1&&(e=!0);
```

**Comment by jtbr** [comment]
The same issue (that the icons fail to be viewable) occurs when there is a `./` in the path, eg: `./icons/icon.data.svg.css`.

I've modified the code from pstenstrm to fix this case as well as the `../` case:
```javascript
    for(var e,n=0;u.length>n;n++)u[n].href&&u[n].href.indexOf(t.replace(/\.+\//g,''))>-1&&(e=!0);
```
Good job with this pstenstrm.

**Comment by pjacquemin** [comment]
I have fixed this removing "../" with replace()
app.js is the name the javascript file containing this code itself :  
`$(document).ready(function(){
    var jsFileLocation = $('script[src*=app]').attr('src');  // the js file path = /Content/js/app.js
    jsFileLocation = jsFileLocation.replace('js/app.js', '');   // the js folder path = /Content/js/

    // Grunticon
    grunticon([jsFileLocation + "img/svg/icons.data.svg.css", jsFileLocation + "img/svg/icons.data.png.css",
                jsFileLocation + "img/svg/icons.fallback.css"]);
});`
