### ISSUE TITLE
Wrong destination folder

### ISSUE THREAD

**Issue by mathg** [filamentgroup/grunticon#237]
Hi!

I'm not sure whether this is a bug or a problem with my configuration, but when I run the grunticon task, the output isn't where it should be. The tasks creates one extra directory in my dest folder named after the first icon in the list and then outputs everything into that directory.

Here is my task :

```
grunticon: {
    icons: {
        files: [{
            expand: true,
            cwd: 'svg/min',
            src: ['**/*.svg', '**/*.png'],
             dest: 'dist/output'
        }],
        options: {
            enhanceSVG: true,
            loadersnippet: "grunticon.loader.js"
        }
    }
}
```

Here is what is being outputted.

![output](https://cloud.githubusercontent.com/assets/204186/6372290/0ced2daa-bcd1-11e4-9667-a7d822069ae7.jpg)

While testing what was going on I noticed that on line 79 of grunticon.js the config.dest is being set to this value : config.dest = this.files[0].orig.dest; 

This is where the global dest is being changed to the name of the first icon instead of what I wrote in my gruntfile. If I change it to config.dest = this.files[0].orig.orig.dest; it works fine.

Thank you for your help and great work on this!

**Comment by jefflembeck** [comment]
Which Windows version, Node version, Grunt version, and Grunticon version are you on?

**Comment by mathg** [comment]
Windows 7 Pro SP1 64 bits
Node v0.10.31
Grunt 0.4.5
Grunticon 2.1.2

**Comment by jefflembeck** [comment]
@mathg Thanks! I'll see what I can do to replicate.

**Comment by gideonheilbron** [comment]
Hi @jefflembeck . Just to let you know @mathg isn't the only one having this problem, I'm running into the same issue while using a newer version of Grunticon on Windows 8.1. More details: 

Windows 8.1 Pro
Node: 0.10.36
Grunt: 0.4.5
Grunticon: 2.1.5

Thank you!

**Comment by fschroiff** [comment]
@mathg @gideonheilbron I had the same issue on a Mac and fixed it by disabling `grunt-newer` for the grunticon task.

**Comment by mathg** [comment]
@fschroiff  Thanks a lot! This did the trick for me as well.

**Comment by BenHaldenby** [comment]
@fschroiff Thanks, I was having the same problem on OS X and disabling grunt-newer fixed it for me. Anyone figured out why it's happening?
