### ISSUE TITLE
Null path for phantomjs

### ISSUE THREAD

**Issue by phlorie** [filamentgroup/grunticon#239]
Hi

I can't find my issue anywhere. I think I might have missed something in the configuration. When I run the task, I have this output. 

```shell
Running "grunticon:myIcons" (grunticon) task
svg-to-png now spawning phantomjs...
(using path: null)
```

It seems that running
```shell
npm install grunt-grunticon --save-dev
```
did not add grunticon as a dependency in package.json.
Adding it manually doesn't solve the problem.
I had several issues before which seemed to be due to dependencies (jshint for example) when I followed the exact steps for installation in the documentation.
Something is definitely happening in the output folder, but a lot of files are still missing.

Thank you for your help.

Also, I am really trying to understand how the dependencies work.
In the readme, it is said we can add
```shell
grunt.registerTask('default', ['jshint', 'qunit', 'concat', 'uglify', 'grunticon:myIcons']);
```
But when I do so, grunt just can't find the jshint task. Does it mean it has to be installed and created ? I couldn't find the information anywhere.

**Comment by jefflembeck** [comment]
So, it looks like phantomjs didn't install properly for you. And it seems like there might be other issues at hand here. 

Did you run `npm install grunt-grunticon --save-dev` from inside the project directory?

If so, what does your package.json look like after?

**Comment by phlorie** [comment]
I definitely ran this command in the project directory.
The line corresponding to grunticon wasn't added in package.json so I added it manually.
What I did then, was just removing the grunt-gunticon folder from node_modules.
I kept the Gruntfile.js and package.json as is then ran the install again.
It is now working but there are a lot of weird things that happened.
I hope it will keep working.
So the jshint task and the others should be able to run if it is properly installed?

**Comment by jefflembeck** [comment]
yeah, it looks like phantomjs hiccuped on your initial install.

And yes, in order for jshint, etc. to work, you'll want to make sure they are properly installed and there are grunt tasks set up for them. The README example is just an example of a typical setup.

If you'd like to report the issues where weird things are happening, feel free to open up another issue. I'll close this one for now. Thanks!

**Comment by stevenwoodson** [comment]
Wanted to comment on this as I had the same issue and the only thing that worked for me was running ```npm install grunt-grunticon --save-dev``` prefaced with ```sudo```

I didn't get any different installation logs that I could see, so I don't know what wasn't getting added correctly without sudo permission.

**Comment by frdmn** [comment]
Had to update  `npm` using:

    $ npm install -g npm

**Comment by icoach** [comment]
It seems that in some cases phantomjs dependency of grunt-grunticon doesn't work. I had to delete it and install phantomjs manually. Now everything works as expected.

**Comment by lnegi** [comment]
It worked for me by doing the below 

- Update the node to the latest version
- remove the node_modules folder
- run npm install 

After that instead of complaining path: null, its showing the path : 

Running "grunticon:icons" (grunticon) task
svg-to-png now spawning phantomjs...
(using path: /Users/lnegi/Documents/WORK/myapp/node_modules/phantomjs/lib/phantom/bin/phantomjs)

**Comment by andalusi** [comment]
On my local machine it works as expected, unfortunately on my live server I got (using path: null).
npm 3.8.6
node v5.10.1

I tried all the advised above but noting worked out.
Any help would be much appreciated.
