### ISSUE TITLE
ability to disable certain options?

### ISSUE THREAD

**Issue by stratboy** [filamentgroup/grunticon#240]
Hi! I basically use only the icons.data.svg.css file. So it would be great if I had one or more options to  disable the other files generation :)

Thank you, regards!

**Comment by jefflembeck** [comment]
In order to generate the icons.data.svg.css file, we use https://github.com/filamentgroup/directory-encoder (https://github.com/filamentgroup/grunticon/blob/master/tasks/grunticon.js#L187).

It's a pretty straight-forward library for this use and will cut out the rest of the cruft.

Thanks!
