### ISSUE TITLE
CSS source order

### ISSUE THREAD

**Issue by oskarrough** [filamentgroup/grunticon#241]
Hi, as the grunticon loader injects the `icons.data.xxx.css` files before my `main.css` the icon styles are getting overridden by CSS specificity.

Would it be possible to tell the loader to append the css files to the header instead of prepending?

**Comment by zachleat** [comment]
See the `before` option added to loadCSS in this PR: https://github.com/filamentgroup/grunticon-lib/pull/14

This will be included with 3.0
