### ISSUE TITLE
PNG output faulty

### ISSUE THREAD

**Issue by medienkrank** [filamentgroup/grunticon#242]
Hi,

my png output contains the correct filenames, but these files don´t include the correct color informations. They include the svg code in black letters. That looks creepy. The dimensions of the files vary according to the size of the svg code length.

I´m using this code in my gruntfile. But the result is the same with the standard code from the docs.

```javascript
grunticon: {
        build: {
            files: [{
                expand: true,
                cwd: 'assets/img/svg',
                src: ['*.svg'],
                dest: "assets/css/embed"
            }],
            options: {
                enhanceSVG: true,
                cssprefix: '.img-',
                datasvgcss: "img.data.svg.css",
                datapngcss: "img.data.png.css",
                urlpngcss: "img.fallback.css",
                pngfolder: "../../img/png",
                pngpath: "../../img/png",
                compressPNG: true,
                
            }
        }
    },
```

**Comment by jefflembeck** [comment]
Can you upload what one of the PNGs looks like?

**Comment by medienkrank** [comment]
Here is one of the fallback PNGs

![logo-inverse](https://cloud.githubusercontent.com/assets/8894989/6421819/be023d1c-bed2-11e4-91fe-061f1344580f.png)

**Comment by jefflembeck** [comment]
@medienkrank are you running the svgs through svgmin before you run them through svg-to-png?

**Comment by medienkrank** [comment]
Yes i´m using svgmin before grunticon. 
```
grunt.registerTask('img', ['svgmin', 'grunticon:build']);
```

**Comment by jefflembeck** [comment]
@medienkrank yeah, this is an issue with svgmin stripping some things it shouldn't. Check out this comment on the same issue - https://github.com/filamentgroup/grunticon/issues/171#issuecomment-59124444 to see which options to use to make sure this can be avoided

**Comment by agorilla** [comment]
Thanks @jefflembeck for the hint.

My colleagues had the same issue on their Windows PCs. 
Of course on my Mac everything worked fine with the default svgmin options.
