### ISSUE TITLE
Task fails if processing multiple "colors" files

### ISSUE THREAD

**Issue by niksy** [filamentgroup/grunticon#244]
When trying to process multiple "colors" files (e.g. `foo.colors-white-red.svg`, task fails with the following message:

``` sh
Fatal error: Property 'ending' of object #<Farm> is not a function
```

Running the task on normally named files processes them successfully.

I think it has something to do with PhantomJS because that’s the last process I saw inside Terminal window.

**Comment by johnbender** [comment]
@niksy 

Thanks for reporting this, we just made an update to use `workerFarm` which is likely causing this. Will take a look on Monday.

**Comment by niksy** [comment]
In the meantime, can I revert to some previous version which doesn’t have this bug?

**Comment by johnbender** [comment]
https://github.com/filamentgroup/grunticon/releases

Looks like 2.1.4 or 2.1.3 should work since they depend on the earlier version of `directory-colorify`.
