### ISSUE TITLE
Responsive fallback images via CSS media queries

### ISSUE THREAD

**Issue by timrourke** [filamentgroup/grunticon#245]
Grunticon is awesome! I love it so much that I'd like to bug you guys about a feature or two.

I think it would be great if the fallback images could be optionally generated in multiple sizes, to use in conjunction with srcset/Picturefill. I realize this may add some bloat to the fallback image URI stylesheet, nullifying the performance benefit of only downloading one fallback css file for the job. Is there any way to do this already with directory encoder? 

Making additional fallback pngs of multiple sizes is trivial with grunt-responsive-images, but the challenge lies in creating a set of media queries to swap out the background-image url to best fit the viewport based on a set of predefined width values.

Additionally, I think the plugin would greatly benefit from an option to add styles to the fallback stylesheet that would ensure the '.icon-...' elements were sized in the browser via css according to their source SVG's original aspect ratio. I'm imagining a method that would use the 'width:100%;height:0;padding-bottom:Y%;' css approach to create elements that fit within their container element while retaining their natural aspect ratio. Thy 'Y%' would be derived from the source SVG's viewBox's height divided by the source SVG's viewBox's width.

The use case for this feature would be a scenario where a design implements SVGs in a wide variety of shapes and sizes not restricted to a 1:1 icon implementation.

I'm not sure I'm the right person to tackle these feature, and I'm definitely not sure they are relevant to the typical use case of the plugin, but to me they would be welcome additions to my SVG workflow. Thanks for your thoughts and amazing work!

**Comment by zachleat** [comment]
This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for enhancements. This means enhancement issues will now be closed instead of leaving them open.

View [the enhancement backlog here](https://github.com/filamentgroup/grunticon/issues?utf8=%E2%9C%93&q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+). Don’t forget to upvote the top comment with 👍!
