### ISSUE TITLE
'Task "grunt-grunticon" not found.' immediately after running 'npm install grunt-grunticon --save-dev'

### ISSUE THREAD

**Issue by edadams** [filamentgroup/grunticon#248]
Hi there. Really, really sorry as this is probably a total newbie thing and I'm quite likely making some silly error, but for some reason I get a console error saying:

````Warning: Task "grunt-grunticon" not found. Use --force to continue.````

...Every time, **immediately after** I run: 

````npm install grunt-grunticon --save-dev````

I'm not sure what I'm doing wrong, as when I go to the folder where I've been running these commands I see a folder called `node_modules`, inside of which is a directory called `grunt` and another called `grunt-grunticon`, and the grunticon one appears to have what it needs.

I am running Node v0.10.22, Grunt v0.4.5, and Grunt-cli v0.1.13.

Here's my Gruntfile.js:
 
````javascript
module.exports = function(grunt){
  grunt.initConfig({
    pkg: grunt.file.readJSON('package.json'),
    grunticon: {
      myIcons: {
        files: [{
          expand: true,
          cwd: 'source',
          src: ['*.svg', '*.png'],
          dest: 'output'
        }],
        options: {
          enhanceSVG: true
        }
      }
    }  
  });

  grunt.loadNpmTasks('grunt-grunticon');

  grunt.registerTask('default', ['grunt-grunticon']);
};
````

Here's my package.json: 

````javascript
{
  "name": "edgrunticon",
  "version": "0.1.0",
  "devDependencies": {
    "grunt": "~0.4.5",
    "grunt-grunticon": "~2.1.5"
  }
}
````

**Comment by jefflembeck** [comment]
Hey @edadams - a quick change in your Gruntfile _should_ get you there:

```
module.exports = function(grunt){
  grunt.initConfig({
    pkg: grunt.file.readJSON('package.json'),
    grunticon: {
      myIcons: {
        files: [{
          expand: true,
          cwd: 'source',
          src: ['*.svg', '*.png'],
          dest: 'output'
        }],
        options: {
          enhanceSVG: true
        }
      }
    }  
  });

  grunt.loadNpmTasks('grunt-grunticon');

  grunt.registerTask('default', ['grunticon']); // THIS SHOULD FIX IT
};
```

Let me know if this doesn't work for you. Thanks!

**Comment by edadams** [comment]
It works now, thank you! I don't know where I got the idea that I had to type `grunt-grunticon` to run the task, but thanks for helping me. <3
