### ISSUE TITLE
dynamicColorOnly: true outputting original icon

### ISSUE THREAD

**Issue by iparr** [filamentgroup/grunticon#252]
I have the following:

```
options: {
    datasvgcss: 'icons.data.svg.scss',
    datapngcss: 'icons.data.png.scss',
    urlpngcss: 'icons.fallback.scss',
    cssprefix: '.icon--',
    dynamicColorOnly: true,
    colors: {
        white: "#fff"
    }
}
```

…and the file `fvg-logo.colors-white.svg`.

Unfortunately this still outputs the CSS (and SVGs, etc.) for `.icon--fvg-logo-white` _and_ `.icon--fvg-logo`.

Ideally I'd like the `.icon-fvg-logo` selector to be the white logo and for there only to be one icon in one color.

Isn't that how this is supposed to work? Have I misunderstood?

This is obviously not a gamebreaker, but it could grow and grow into a slightly annoying problem.

I'm on version 1.3.1.

**Comment by jefflembeck** [comment]
Yeah, this is an older bug - https://github.com/filamentgroup/grunticon/issues/195

You can fix this by updating to the latest and greatest Grunticon (2.1.6) or you can use 1.6

**Comment by iparr** [comment]
oh, I did search but couldn't find. doh. Thank you for your help!

**Comment by iparr** [comment]
I'm on 2.1.6 now, but with same details as before, I'm now getting one selector to use (`.icon--fvg-logo-white`) but this icon is now black (like the original). I have to change color manually by editing the SVG and when I disable `dynamicColorOnly`, I get two selectors, both of which provide an identical black icon.

Can this be re-opened?

**Comment by jefflembeck** [comment]
Yeah. I can reopen, but I'm unable to reproduce this locally, so I'll need some help:

What is your:
- OS
- Node Version

And can I get the svg that you're using?

**Comment by iparr** [comment]
Cheers @jefflembeck 

* OS: OSX 10.9.5
* Noder Version: v0.10.29
