### ISSUE TITLE
dynamicColor should emit warning?

### ISSUE THREAD

**Issue by andrewmh** [filamentgroup/grunticon#253]
I ran into an issue where a developer added an icon "checkmark.svg" where we already had a dynamic color icon "checkmark.colors-green.svg". The class generated for the first checkmark ended up overriding the original checkmark color icon. 

Would it may make sense to add some warning or error that could be emitted in a case where the same class is generated twice?

**Comment by jefflembeck** [comment]
Yeah, given that directory-encoder throws an error if there are two files of the same name (but different types) because of this issue, I can see the use here.

**Comment by andrewmh** [comment]
I'm happy to take care of it. I'm not familiar with the code at all so I'd need some direction on where to go.
