### ISSUE TITLE
data-grunticon-embed doesn't work?

### ISSUE THREAD

**Issue by greenthoms** [filamentgroup/grunticon#255]
Tried using `data-grunticon-embed` with v2.1.6 but couldn't get it working.

Cloned the repo, did an npm install then Grunt. Loaded the preview.html in Chrome but no dice.

![screen shot 2015-04-13 at 3 35 39 pm](https://cloud.githubusercontent.com/assets/4131389/7110383/54aeea6a-e1f3-11e4-87d6-c019f5260e92.png)

Also getting a console error in the head:
`Uncaught TypeError: Cannot read property 'length' of null`

Is this an issue or am I missing a step?

**Comment by jefflembeck** [comment]
@tomgzip so, I could see this happening in situations where you're trying to run this as a local file in your browser, instead of at at URL (via some local webserver).

CORS restrictions on Chrome will not allow you to access the CSS file that has the SVG data that you want in it.

The line in question is here: https://github.com/filamentgroup/grunticon/blob/master/tasks/grunticon/static/grunticon.embed.js#L41

So, the best quick option is to set up the project in a virtual host and serve it behind a webserver (like Apache). That will allow Chrome to handle this.

On our end, we should: A. Document this issue in how to set-up the project and B. Make sure this doesn't blow up, just in case.

**Comment by tomgzip** [comment]
@jefflembeck Yep thats it. I setup a local webserver (I just used MAMP) and the embed attribute worked.

Personally, I found the explanation the "loader" in the ReadMe a little unclear. It's my time trying Grunticon so I wasn't familiar with how it worked in earlier versions. However, I'm not super experienced with Grunt or JS in general.

Appreciate the reply, happy to close if this is a documentation improvement/enhancement. 

Loving Grunticon, great work team :+1:

**Comment by jefflembeck** [comment]
Documentation issues are just as important as code issues!

If you've got anything you'd like to see in there that would make anything clearer, I'd be happy to add it or, if you know a good way to word it, I'd LOVE to see a pull request :)

**Comment by benjgorman** [comment]
I'm also having issues with data-grunticon-embed. I've tried running it locally and on my webserver and nothing seems to give in either Chrome or Safari.


My Gruntfile.js
```
module.exports = function(grunt) {
	// Project configuration.
	grunt.initConfig({
		grunticon: {
			myIcons: {
					files: [{
						expand: true,
						cwd: 'grunt/svgs',
						src: ['*.svg', '*.png'],
						dest: "grunt/output"
					}],
				options: {
					loadersnippet: "grunticon.loader.js",
					enhanceSVG: true,
				}
			}
		}
	});
	grunt.loadNpmTasks('grunt-grunticon');
	grunt.registerTask('default', ['grunticon:myIcons']);
};
```

In my header I've got 

```
<script>
	/* grunticon Stylesheet Loader | https://github.com/filamentgroup/grunticon | (c) 2012 Scott Jehl, Filament Group, Inc. | MIT license. */
	window.grunticon=function(e){if(e&&3===e.length){var t=window,n=!(!t.document.createElementNS||!t.document.createElementNS("http://www.w3.org/2000/svg","svg").createSVGRect||!document.implementation.hasFeature("http://www.w3.org/TR/SVG11/feature#Image","1.1")||window.opera&&-1===navigator.userAgent.indexOf("Chrome")),o=function(o){var r=t.document.createElement("link"),a=t.document.getElementsByTagName("script")[0];r.rel="stylesheet",r.href=e[o&&n?0:o?1:2],a.parentNode.insertBefore(r,a)},r=new t.Image;r.onerror=function(){o(!1)},r.onload=function(){o(1===r.width&&1===r.height)},r.src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///ywAAAAAAQABAAACAUwAOw=="}};
	grunticon(["<?php echo get_template_directory_uri(); ?>/grunt/output/icons.data.svg.css", "<?php echo get_template_directory_uri(); ?>/grunt/output/icons.data.png.css", "<?php echo get_template_directory_uri(); ?>/grunt/output/icons.fallback.css"], grunticon.svgLoadedCallback );
	</script>
	<noscript><link href="<?php echo get_template_directory_uri(); ?>/grunt/output/icons.fallback.css" rel="stylesheet"></noscript>
```

and on my page I'm using this, icon appears fine but isn't embedded with svg data.

```
 <div class="icon-twitter" style="width: 50px; height: 50px; background-size:50%;" data-grunticon-embed></div></a>
```

**Comment by benjgorman** [comment]
Got this to work turns out I was using the wrong version of Grunticon! 

Would be nice to see in the documentation ways of checking which version you have installed.

**Comment by jtbr** [comment]
I've had this problem with chrome's stringent CORS restrictions on local content as well.

A simpler workaround than running a local web server is to run chrome with the ```--allow-file-access-from-files``` option. Why this is not the default is beyond me (neither IE nor firefox have this problem under windows [I'd be curious safari works on a Mac]).

If however, you'd like to be able to distribute a working local, static website (as I would), then you can test whether you're running locally in chrome. In Javascript it's a simple test:

        (!!window.chrome && window.location.protocol=='file:')

Just don't try to embed the icons in that case (and fallback to background svg images).

**Comment by jtbr** [comment]
Just to follow up, it appears Safari disables CORS restrictions for local files as well according to [sources](http://stackoverflow.com/questions/29947585/local-ajax-call-to-remote-site-works-in-safari-but-not-in-other-browsers) on the web. So it's pretty much just chrome that's an issue.
