### ISSUE TITLE
data-grunticon-embed not working, no js error

### ISSUE THREAD

**Issue by akmur** [filamentgroup/grunticon#256]
Hello, I am developing using a local environment and I am willing to use your grunticon task.
It runs fine, and everything works except for the data-grunticon-embed which is not outputting any inline svg.
There is no console error, and the embed simply doesn't work.
How could I investigate this further?

Attached is a screenshot which might (or might not) be helpful.

Many thanks

![home - test wp 2015-04-13 10-07-56](https://cloud.githubusercontent.com/assets/957841/7111909/0230d286-e1c5-11e4-9382-b04f43e32038.png)

**Comment by akmur** [comment]
I'm stupid, I was using data-grunticon-embed as a class... sorry for opening an issue for this

**Comment by jefflembeck** [comment]
Glad you got it figured out, thanks!
