### ISSUE TITLE
png image contains source code as image on windows

### ISSUE THREAD

**Issue by gijsroge** [filamentgroup/grunticon#257]
This happens when the `<?xml version="1.0" encoding="utf-8"?>` is missing.

It's somewhat related to https://github.com/filamentgroup/grunticon/issues/171 . However the source svg is already missing the xml tag because its generated by photoshop's Generator.

Not sure if this could be solved in grunticon or this is more an issue that photoshop has to resolve?

**Comment by jefflembeck** [comment]
This is an issue with Windows outright. Without that line, it doesn't handle rendering the SVG correctly as a PNG.

Unfortunately this isn't something we can do anything about on our end.

I'll ask around to see if there are any options in Photoshop to make this not happen (I know Illustrator-created SVGs work wonderfully).

**Comment by gijsroge** [comment]
As far as I know there are no options. They removed it on purpose because some user's couldn't use it in a php include because of the <?xml?> tag

https://github.com/adobe-photoshop/generator-assets/issues/191
