### ISSUE TITLE
data-grunticon-embed solution for dynamically created DOM

### ISSUE THREAD

**Issue by wrench7** [filamentgroup/grunticon#258]
I'm interested in using the data-grunticon-embed functionality in grunticon 2 but as it stands there is no way to have new DOM elements automatically trigger the correct embedding of the SVG. For Angular applications that make use of ng-if for example, or switching entire views in and out of an app, the data-grunticon-embed approach doesn't work.

Am wondering if this is functionality that could be added or whether a separate standalone solution is a better approach?

**Comment by jefflembeck** [comment]
This is definitely something we're looking into.

For now, there are some methods on the `grunticon` object in the loader that might help you:

https://github.com/filamentgroup/grunticon#grunticon-loader-methods

The most likely is:

```JavaScript
grunticon.embedIcons(grunticon.getIcons(grunticon.href));
```

**Comment by timbofield** [comment]
Seems you need to call getCSS on grunticon.href first. 

`grunticon.embedIcons(grunticon.getIcons(grunticon.getCSS(grunticon.href)))`

**Comment by CoolJazzInc** [comment]
I would also like to see this functionality.
Running 'embedIcons' again for the entire DOM after a DOM update is a solution but it's not a very nice one.

Something like an extra 'scope' argument for the embedIcons method would be nice. Where scope would be some node and embedIcons would only run on that node, instead of on document.

**Comment by tannerhodges** [comment]
+1. 

@timbofield Good call on `getCSS`. That saved me some headaches.

I'm using grunticon for dynamic icons in an Angular app. For now, just made a helper with what y'all have already said:

```
/**
 * Callback for embedding Grunticon SVGs
 * https://github.com/filamentgroup/grunticon/issues/213#issuecomment-76323760
 */
function embedSvgs() {
    grunticon.embedIcons(grunticon.getIcons(grunticon.getCSS(grunticon.href)));
}
```

And calling it after the `$digest` cycle as needed:

```
$scope.$evalAsync(function() { // Fire after $digest
    embedSvgs();
});
```

Still pretty new to Angular, so I'm not sure how this should work in a directive, service, or what. Any tips would be awesome.

But yeah, I can't think of a better way to handle this directly in Grunticon other than just adding a method to the global `grunticon` object to do just this. Maybe `grunticon.autoEmbedIcons()`? Or perhaps letting  `grunticon.embedIcons()` default to this kind of auto-lookup?

**Comment by dkeeghan** [comment]
I'm trying to do something similar where we have code AJAX loaded into the page after the initial page load and I need to run something to add the new embed SVGs into the page. 

Running:
```grunticon.embedIcons(grunticon.getIcons(grunticon.getCSS(grunticon.href)));```
Causes the following error in the JS console:
```Uncaught TypeError: Cannot read property 'sheet' of null(…)```

Also, just running:
```grunticon.getIcons(grunticon.href)```
returns a blank object (`{}`)

**Comment by dominikwilkowski** [comment]
:+1: for a fix or clear path as how to manage it.

**Comment by navad** [comment]
We created a simple Angular directive to embed Grunticon SVG's in our app:
https://gist.github.com/navad/c6da12424ef9bc573700

Hope it helps anyone

**Comment by slashadmin** [comment]
+1

Having the same issue as @dkeeghan 
```
grunticon.embedIcons(grunticon.getIcons(grunticon.getCSS(grunticon.href)));
```
only returns an empty array.
Would love to see a solution here.

**Comment by slashadmin** [comment]
I forgot the `data-grunticon-embed` in my dynamically included span.
After adding it, `grunticon.embedIcons(grunticon.getIcons(grunticon.getCSS(grunticon.href)));` still returns an empty array but the icons are properly embdedded.

**Comment by jharris-westpac** [comment]
As per this issue https://github.com/WestpacCXTeam/GUI-source/issues/144 we built the following directive. 

    /**
     * Embeds GruntIcon SVG into the HTML markup correctly
     */
    coreDirectives.directive('grunticonEmbed', function () {

        return {
            restrict: 'A',
            scope: false,
            link: function ($scope: IGruntIconEmbedScope, $element: ng.IAugmentedJQuery, $attr: ng.IAttributes) {
                
                var backgroundSvg = decodeURIComponent(
                    $element.css('background-image').slice(4, -1).replace(/"/g, "")
                ).split(',');

                // Only replace when decoded data is of type image/svg+xml
                if (backgroundSvg[0].indexOf("image/svg+xml") > -1) {
                    $element.html(backgroundSvg[1]);
                    $element.css("background-image", "none");
                }
            }
        };
    });

A later issue was discovered where the background-image was none, likely due to some async loading of the grunticon svg css. A work around was to remove the loader and embed css files directly. SVG for modern browsers and embedded png for IE8 within a conditional comment.

**Comment by markhbucknell** [comment]
For anyone else that is looking for a solution for Angular (Tested on v6), I had to create this to get this to work: https://gist.github.com/markhbucknell/19edab47bac1fa3bda4a2cbc65b584b9
