### ISSUE TITLE
Class name icon--border causes the function related to data-grunticon-embed to trigger

### ISSUE THREAD

**Issue by ckollars** [filamentgroup/grunticon#260]
I have an SVG file named `border.svg` and the class name that outputs after running grunticon is `icon--border`. When I apply this class to a DOM element it seems to automatically call the function related to the `data-grunticon-emebed` attribute.

I just ended up changing the file name to `fence-border.svg` & class `icon--fence-border` and this resolves the unneeded embed action.

I wasn't sure if there was any reserved namespaces with grunticon?

**Comment by jefflembeck** [comment]
There certainly SHOULDN'T be!

I have a pretty full plate right now but will give this a look next week.

Thanks!

**Comment by jefflembeck** [comment]
@ckollars can you check 2.1.7 and see if this works for you?

**Comment by ckollars** [comment]
@jefflembeck Seems to work fine in my previous setup as well as 2.1.7.
