### ISSUE TITLE
Icons not appearing on Safari/IOS

### ISSUE THREAD

**Issue by madebyrichard** [filamentgroup/grunticon#262]
Hi all,

Im new to GruntIcon - I can get icons to display fine on Chrome and Firefox but they dont display at all on Safari and iPhone/iPad.

There are no errors being thrown and safari registers the svg code in css just fine so it doesnt revert to a fallback PNG... I just cant figure out why the icons wont display!

Any ideas?

Thanks

**Comment by jefflembeck** [comment]
Hey @madebyrichard,

Do you have a test page for this, per chance? (or even a few test SVGs that aren't working?)

**Comment by madebyrichard** [comment]
Hi Jeff

Yes you can view a test page here http://madebyrichard.co/clients/sf/index.html 

The logo doesnt appear, and social media icons in footer also. Thanks for the help on this!

**Comment by jefflembeck** [comment]
Looking at the logo, I can see the issue:

So, Safari/iOS does not allow background images that are SVGs to have PNGs embedded within them. They must be pure SVGs. If you open the SVG file, you can see what I mean (there is a big base64 embedded png in there).

**Comment by madebyrichard** [comment]
I see - They were PNG files that I converted to SVG via the Sketch app. would you happen to know a way to get the PNG out of it? Thanks again

**Comment by jefflembeck** [comment]
I don't off of the top of my head, but embedding the SVG in the page might help you out.

If you're using a 2.x version of grunticon, you can do that by putting the `data-grunticon-embed` option on the logo element and then setting the `enhanceSVG` option in your Gruntfile when building. This will create a new loader that you'll use.

**Comment by madebyrichard** [comment]
thanks Jeff

**Comment by johnbender** [comment]
I'm going to close this one, but please re-open if I've done so in error!
