### ISSUE TITLE
How to use customselectors and manage what should be embedded and what is background

### ISSUE THREAD

**Issue by dominikwilkowski** [filamentgroup/grunticon#263]
Hi there,

I have a set of icons I am using and some of them are used with the `data-grunticon-embed` option and some need to be a background-image. I can easily manage that with the `grunticon.svgLoadedCallback` method in the loader and the data attribute.

Unfortunately I also have some custom selectors that I'm adding via:
```json
{
	"checkbox-off": [".checkbox-input + .checkbox-text"],
	"checkbox-on": [".checkbox-input:checked + .checkbox-text"]
}
```
and I would expect them to be background images as the selected element does not have the data attribute on it. It does however replace the `checkbox-text` elements content with the svg.

I may have missed something in the docs but I can't seem to find a way to manage that?

Thanks for the help and this great tool btw

**Comment by jefflembeck** [comment]
Yeah, looks like this is a bug. Thanks! custom selectors are automatically being embedded by the loader currently

**Comment by dominikwilkowski** [comment]
:+1: Is that on the roadmap now?

**Comment by jefflembeck** [comment]
Yes. I haven't scheduled it yet, because I'm behind on some other stuff, but hopefully will have some time to fix this in the next few weeks

**Comment by dominikwilkowski** [comment]
:+1:

**Comment by johnbender** [comment]
@dominikwilkowski 

If you can reference master in your `package.json` for your grunticon dependency you might give this version a try to see if it fixes your issue. 

Thanks!

**Comment by jefflembeck** [comment]
This fix is in on 2.1.7

**Comment by dominikwilkowski** [comment]
Thanks guys, this works marvellously.

**Comment by johnbender** [comment]
@dominikwilkowski 

Great! 

Thanks very much for posting the issue.
