### ISSUE TITLE
Cannot install grunticon due to some dependency changes in directory-colorfy

### ISSUE THREAD

**Issue by hazmi** [filamentgroup/grunticon#266]
When I tried to install, i got the following:

```
npm ERR! 404 404 Not Found: filamentgroup
npm ERR! 404 
npm ERR! 404 'filamentgroup' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'directory-colorfy'
```

Maybe because of this?
https://github.com/filamentgroup/directory-colorfy/commit/3ec765d7fe1f88ab6c190e6f36671641e807566e#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

**Comment by johnbender** [comment]
@hazmi 

It's a problem with the version of NPM that you're running. You'll need to upgrade to at least 2.7. Sorry for the inconvenience.

**Comment by hazmi** [comment]
@johnbender 

Ah, yes, you're right! Im still using the old version of NPM. I've upgraded to the latest and it works just fine now.

Thanks!

**Comment by johnbender** [comment]
@hazmi 

Not a problem. I expect this will be a issue for quite a few people so having this here as documentation will be good!
