### ISSUE TITLE
svg-to-png now spawning phantomjs...

### ISSUE THREAD

**Issue by bramwillemse** [filamentgroup/grunticon#270]
Hi, 

I'm running into a freezing grunticon task (see below):

```
Running "grunticon:build" (grunticon) task
svg-to-png now spawning phantomjs...
(using path: C:\<WORKINGDIR>\node_modules\grunt-grunticon\node_modules\
grunticon-lib\node_modules\svg-to-png\node_modules\phantomjs\lib\phantom\phantom
js.exe)
```

**Gruntfile.js**

```
/** 
 * SVG / PNG conversion
 */
grunticon: {
    build: {
        files: [{
            expand: true,
            cwd: 'includes/img/input',
            src: ['*.svg', '*.png'],
            dest: 'includes/img/output'
        }],
        options: {
            enhanceSVG: true,
            compressPNG: true,
            pngpath: 'includes/img/png'
            // defaultWidth: '64px',
            // defaultHeight: '64px',
        }
    }
},  
```

**Specs**
- Windows 7
- Grunticon  2.1.0
- npm v2.10.1
- phantomjs 1.9.17
- full permissions for SYSTEM and my account
- without SVG in input folder, there's no freeze

When I try to list phantomjs I get the following message + error: 

```
C:\WORKINGDIR>npm list phantomjs
kvk-2015@0.2.0 C:\WORKINGDIR
├─┬ grunt-grunticon@2.2.0
│ └─┬ grunticon-lib@1.0.2
│   ├─┬ directory-colorfy@2.0.5
│   │ └── phantomjs@1.9.15
│   └─┬ svg-to-png@2.0.0
│     └── phantomjs@1.9.17
└── phantomjs@1.9.17  extraneous

npm ERR! extraneous: phantomjs@1.9.17 C:\WORKINGDIR\node_modules\phan
tomjs
```

**Permissions**
I've updated all file permissions to full. Still nothing.

**Comment by bramwillemse** [comment]
PS
I'm aware of other threads about this. Trying to fix file permissions right now. But still, no errors and a full freeze is worth a new issue..

**Comment by jefflembeck** [comment]
`npm ERR! extraneous` means a package is installed but is not listed in your project's package.json. npm is going to have a problem with this.

**Comment by bramwillemse** [comment]
@jefflembeck But phantomjs is already installed twice as a dependency within the grunticon module. So that shouldn't be the problem freezing my grunt task, right?

**Comment by jefflembeck** [comment]
@bramwillemse it absolutely shouldn't be freezing. That part I agree with.

I'll open up an issue over on svg-to-png about this and will try to see when I can get to it.

**Comment by bramwillemse** [comment]
@jefflembeck Okay, thanks a bunch!
