### ISSUE TITLE
npm install grunt-grunticon does not work

### ISSUE THREAD

**Issue by crohrer** [filamentgroup/grunticon#271]
I get this error on multiple machines when I try to install grunticon:
```
$ npm install grunt-grunticon --save-dev
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "grunt-grunticon" "--save-dev"
npm ERR! node v0.10.38
npm ERR! npm  v2.8.3

npm ERR! Cannot read property 'dependencies' of undefined
```

**Comment by jefflembeck** [comment]
@crohrer ok, so - I'm on Yosemite (OSX 10.10.3 to be exact, which is a newer version of Darwin than I'm seeing in your error) and grabbed node v0.10 and npm v2.8 and wasn't able to reproduce.

That leads me to believe this is an OSX + node v0.10 problem.

Ok - there are a couple of ways you can possibly fix this:

1. Upgrade to node 0.12
2. `ulimit -n 2560`

Let me know if you try one of those and it doesn't help!

**Comment by crohrer** [comment]
Thanks! 
upgrading node to v0.12.5 fixed it for me
