### ISSUE TITLE
Icons disappear using ajax and svgLoadedCallback in Safari/PC 

### ISSUE THREAD

**Issue by fckd** [filamentgroup/grunticon#273]
I load additional content including icons via ajax into my page. After successful ajax call I would like to call `svgLoadedCallback` to enable hover-styles on newly injected icons. When I do Safari on PC hides all icons on the page.
It works without the call to `svgLoadedCallback`, but then there's no hover for the injected icons.

Setup: Windows 7, Safari 5.1.7
Here is a testpage: http://claudiuskirsch.com/grunticon/
The first links works fine but has no hover state, second links hides all icons.

Cheers, Claudius

**Comment by jefflembeck** [comment]
I'll take a look at this, but given that the latest version of Safari for Windows is almost 5 years old, if I can't recreate this in another browser, it might take some very low priority.
