### ISSUE TITLE
grunticon issue

### ISSUE THREAD

**Issue by highvoltag3** [filamentgroup/grunticon#276]
Grunt-icon can't be installed it gives a 404 Not Found: filamentgroup someone reported the same issue to NPM tho I don't think it has to do with them.

See NPM [Bug Report](https://github.com/npm/npm/issues/8651)

**Comment by jefflembeck** [comment]
grunt-grunticon depends on a package (directory-colorfy) which depends on a scoped package.

Updating your version of npm should fix the problem

**Comment by hotrush** [comment]
```npm update -g``` helped to me

**Comment by jefflembeck** [comment]
As @hotrush said, This is an issue with your npm version. Namespaced modules are not available until 2.x. You can update it with npm install -g npm@latest
