### ISSUE TITLE
Visual Studio  - Grunticons errors on install

### ISSUE THREAD

**Issue by MelanieLinares** [filamentgroup/grunticon#277]
Running Visual Studio 2013 with the below packages:

Id                             Version              Description/Release Notes                                                                                          

---

AjaxControlToolkit             4.1.50508            The Ajax Control Toolkit contains a rich set of controls that you can use to build highly responsive and interac...
Braintree                      2.41.0               Braintree client library  
Grunt.js                       0.4.2.6              The JavaScript Task Runner....  
Node.js                        0.10.36              Node.js uses an event-driven, non-blocking I/O model that makes it lightweight and efficient, perfect for data-i...
Npm.js                         1.3.15.10            a package manager for node....  
recaptcha                      1.0.5.0              reCAPTCHA is a free CAPTCHA service that helps to digitize books, newspapers and old time radio shows.             

Grunt was installed via NuGet extension as a part of Visual Studio.
Following the github docs (https://github.com/filamentgroup/grunticon#getting-started) I type in the command "npm install grunt-grunticon --save-dev" and the errors start spilling out in a loop. They don't stop automatically. I have also tried "npm install grunt-grunticon" with the same results.

npm : npm WARN package.json example-project@0.1.0 No description
At line:1 char:1
- npm install grunt-grunticon --save-dev
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (npm WARN packag... No description:String) [], RemoteException
  - FullyQualifiedErrorId : NativeCommandError

npm
 WARN
 package.json
 example-project@0.1.0 No repository field.

npm
 WARN
 package.json
 example-project@0.1.0 No README data

npm
 http
 GET
 https://registry.npmjs.org/grunt-grunticon

npm
 http
 304
 https://registry.npmjs.org/grunt-grunticon

npm
 http
 GET
 https://registry.npmjs.org/grunticon-lib/1.0.2

The errors repeat with other registry.npmjs.org related 304s.

**Comment by jefflembeck** [comment]
This is normally fixed by upgrading npm, as grunticon depends on a library which depends on a private module - I see from the print out above that you're on `Npm.js 1.3.15.10 a package manager for node....`

Can you update your npm version to latest? `npm install -g npm@latest` should do the trick.

Thanks!

**Comment by MelDesignsStuff** [comment]
PM> npm install -g npm@latest

npm : npm http GET https://registry.npmjs.org/npm
At line:1 char:1
+ npm install -g npm@latest
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (npm http GET ht...y.npmjs.org/npm:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
npm
 http
 200
 https://registry.npmjs.org/npm

npm
 http
 GET
 https://registry.npmjs.org/npm/-/npm-2.13.0.tgz

npm
 http
 200
 https://registry.npmjs.org/npm/-/npm-2.13.0.tgz

C:\VS2013 Projects\packages\Node.js.0.10.36\npm -> C:\VS2013 Projects\packages\Node.js.0.10.36\node_modules\npm\bin\npm-cli.js
npm@2.13.0 C:\VS2013 Projects\packages\Node.js.0.10.36\node_modules\npm


By the way I'm not sure if this would be an issue, but I'm using Visual Studio's Package Manager Console.

**Comment by jefflembeck** [comment]
Ok, what happens when you run `npm --version`?

**Comment by MelDesignsStuff** [comment]
PM> npm --version
1.3.15
PM>

**Comment by jefflembeck** [comment]
Ok, so it looks like we have a toolchain problem somewhere (considering you can't update npm), either at the npm level or the VS level.

Filing a bug at https://github.com/npm/npm/issues is likely to net you better results. The underlying issue is that you can't update npm using `npm install -g npm@latest`. Listing your node version and your current npm version, along with your OS and how you install things should help them a lot.
