### ISSUE TITLE
npm ERR! Invalid name: "@filamentgroup/worker-farm"

### ISSUE THREAD

**Issue by ryfy** [filamentgroup/grunticon#280]
Getting an npm error when trying to install on local Yosemite machine.

npm ERR! Darwin 14.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "grunt-grunticon" "--save-dev"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! Invalid name: "@filamentgroup/worker-farm"

Any ideas?

**Comment by jefflembeck** [comment]
Can you install @filamentgroup/worker-farm just regularly?

`npm install @filamentgroup/worker-farm`

If not, can you double-check for me, just to make sure, `npm --version`?

**Comment by ryfy** [comment]
Sure can't. And I'm running npm  v2.11.3

[Related?] (https://github.com/npm/npm/issues/8927)

**Comment by jefflembeck** [comment]
What error do you get? And I sure hope not - I haven't seen this error on machines that don't have a proxy issue and have their npm and node versions updated yet. It's also not something that `npm link` would be used with as far as I know

**Comment by ryfy** [comment]
`43 verbose stack Error: Invalid name: "@filamentgroup/worker-farm"
43 verbose stack     at ensureValidName (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js:300:15)
43 verbose stack     at Object.module.exports.fixNameField (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js:204:5)
43 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/normalize.js:30:38
43 verbose stack     at Array.forEach (native)
43 verbose stack     at normalize (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/normalize.js:29:15)
43 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:338:5)
43 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:113:5)
43 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:178:20
43 verbose stack     at evalmachine.<anonymous>:263:20
43 verbose stack     at OpenReq.Req.done (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:141:5)`

**Comment by ryfy** [comment]
```unix
43 verbose stack Error: Invalid name: "@filamentgroup/worker-farm"
43 verbose stack     at ensureValidName (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js:300:15)
43 verbose stack     at Object.module.exports.fixNameField (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js:204:5)
43 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/normalize.js:30:38
43 verbose stack     at Array.forEach (native)
43 verbose stack     at normalize (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/normalize.js:29:15)
43 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:338:5)
43 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:113:5)
43 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:178:20
43 verbose stack     at evalmachine.<anonymous>:263:20
43 verbose stack     at OpenReq.Req.done (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:141:5)

**Comment by jefflembeck** [comment]
checking if this is a bug in our stuff (over at npm)

**Comment by ryfy** [comment]
reverted to npm v2.10.1 for now and all seems smooth

**Comment by jefflembeck** [comment]
@ryfy that's great news. I'll inform the CLI team

**Comment by iarna** [comment]
Hey, I did a little looking and well, the results are weird. That stack trace does seem to be from npm@2.11.3. In fact, the last time that normalize-package-data was located where that stack trace shows is npm@1.4.19.

Can you try running?

```
node /usr/local/lib/node_modules/npm --version
```

**Comment by pahund** [comment]
I have the same issue. 
Could it be that somewhere in grunticon's dependency tree, there is a dependency to [@filamentgroup/worker-farm](https://www.npmjs.com/package/@filamentgroup/worker-farm) where it should be [worker-farm](https://www.npmjs.com/package/worker-farm)? In the description of `@filamentgroup/worker-farm` it says: "Available in npm as worker-farm".
I resorted to using grunticon version 2.1.6 for now, installation of 2.2.1 is not possible with the current version of npm (I use npm v2.11.2, on OS X Yosemite, Node v0.12.5)

**Comment by jefflembeck** [comment]
@pahund we currently are using a publicly available, name-scoped version of worker-farm (it is a fork of the original). The original does not work for what we are attempting to do.

Have you tried running @iarna's suggestion above?

**Comment by frontendauteur** [comment]
For the sake of chiming in, I was having the same issue yesterday on `npm@2.11.3` and it was relieved when I upgraded to `npm@2.14.1`.

**Comment by jefflembeck** [comment]
@frontendauteur thanks! I'm closing this issue as it's not an issue with grunticon

**Comment by dmonin** [comment]
I have the same problem unfortunately:
```
npm install @filamentgroup/worker-farm
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "@filamentgroup/worker-farm"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
```
is there any recommendation, which may help?

**Comment by jefflembeck** [comment]
@dmonin what happens if you just try to install @filamentgroup/worker-farm ?

**Comment by dmonin** [comment]
@jefflembeck actually, the same:). the module couldn't be found. Could it be that it has something to do with, that it was renamed to node-worker-farm?

https://github.com/filamentgroup/node-worker-farm

**Comment by dmonin** [comment]
Also tried to downgrade to previous stable version, but get the same error:
```
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7

npm ERR! Invalid name: "@filamentgroup/worker-farm"
npm ERR! 

```

**Comment by jefflembeck** [comment]
Unfortunately, that's not the case.

```
$ nvm use 4
Now using node v4.2.2 (npm v2.14.7)
$ npm install @filamentgroup/worker-farm
npm WARN package.json test@1.0.0 No description
npm WARN package.json test@1.0.0 No repository field.
npm WARN package.json test@1.0.0 No README data
@filamentgroup/worker-farm@1.2.0 node_modules/@filamentgroup/worker-farm
├── xtend@4.0.1
└── errno@0.1.4 (prr@0.0.0)
```

(that's with a completely clear cache)

What happens if you run `node /usr/local/lib/node_modules/npm --version`

**Comment by dmonin** [comment]
```
nvm use 4
```
command not found (tried also npm use 4, it shows list of available commands

```
npm --version
```
shows 2.14.7

the same versions as yours (node 4.2.2, npm 2.14.7).

is it stored in standard npm repository?

**Comment by jefflembeck** [comment]
@dmonin yes, it's a scoped module, but it's completely public (or nobody at all would have access to it) - https://www.npmjs.com/package/@filamentgroup/worker-farm

This is definitely bizarre.

Can you run `node /usr/local/lib/node_modules/npm --version` instead of `npm --version`?

**Comment by dmonin** [comment]
yes, i tried it first, but get:
`/usr/local/lib/node_modules/npm: is a directory`

I think it installed in `/usr/local/bin/npm`

**Comment by dmonin** [comment]
`/usr/local/lib/node_modules/npm/bin/npm --version`
shows 2.14.7 as well

**Comment by dmonin** [comment]
I will ask it here: <https://github.com/npm/npm/issues>, as an error message suggest. Seems everything correct to me.

**Comment by M3kH** [comment]
This is also broken for me:
```
 npm install --save @filamentgroup/worker-farm
npm ERR! git clone git@github.com:filamentgroup/worker-farm Cloning into bare repository '/.npm/_git-remotes/git-github-com-filamentgroup-worker-farm-17600d18'...
npm ERR! git clone git@github.com:filamentgroup/worker-farm ERROR: Repository not found.
npm ERR! git clone git@github.com:filamentgroup/worker-farm fatal: Could not read from remote repository.
npm ERR! git clone git@github.com:filamentgroup/worker-farm 
npm ERR! git clone git@github.com:filamentgroup/worker-farm Please make sure you have the correct access rights
npm ERR! git clone git@github.com:filamentgroup/worker-farm and the repository exists.
npm ERR! addLocal Could not install filamentgroup/worker-farm
npm ERR! Error: ENOENT, stat 'filamentgroup/worker-farm'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 14.3.0
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "@filamentgroup/worker-farm"
npm ERR! cwd /
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! path filamentgroup/worker-farm
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /npm-debug.log
npm ERR! not ok code 0
```

Not sure but I think that @ is creating some issues.

**Comment by jefflembeck** [comment]
@M3kH in your case, the npm version you are using is 1.4.28 (which is pretty old).

Try updating to either npm 3 with `npm install -g npm@latest`

Then, run `npm rebuild` and `npm install`

**Comment by manovotny** [comment]
This bit me today too when trying to move off of `grunticon` and onto `grunticon-lib` directly. I thought I'd chime in here versus opening a new issue on `grunticon-lib`.

In my case, I am behind a proxy (gotta :heart: big corporations) and we are also using an internal npm registry.

This is the error I get.

```
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "i" "gulpicon" "--save-dev"
npm ERR! node v0.12.0
npm ERR! npm  v2.14.17

npm ERR! Unexpected token <
npm ERR! <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
npm ERR! <html><head>
npm ERR! <title>404 Not Found</title>
npm ERR! </head><body>
npm ERR! <h1>Not Found</h1>
npm ERR! <p>The requested URL /content/groups/deere-ui-mjd-repositories/@filamentgroup/worker-farm was not found on this server.</p>
npm ERR! </body></html>
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mn42754/Developer/Repositories/deere-ui/deere-ui-icons/npm-debug.log
```

As mentioned above, there does seem to be some "fun" with the `@`. I totally understand why you're using it, but as you can see in the error above, it's trying to look for `@filamentgroup/worker-farm` on our internal npm registry. No other external npm module has produced this error (yet), but this is also the first time we've ever tried to install an external dependency with an `@` in it.

FWIW, I am using node v4.2.4 and npm v2.14.12.

Not sure what I am going to do at this point besides keep Grunt around just for grunticon simply because it's working.

**Comment by jefflembeck** [comment]
@manovotny does your internal npm have a pass through to the main registry? If so, does it work for scoped modules?

**Comment by manovotny** [comment]
@jefflembeck : : 

I have sad news. Well, sad for me at least. Hopefully it will be helpful to others if they wind up here.

We are currently using [Nexus](http://www.sonatype.com/nexus/solution-overview) for our internal npm registry, which unfortunately ***does not*** allow scoped modules. 

They tell me we are close (within 1 - 2 months) of switching to [Artifactory](https://www.jfrog.com/artifactory/), which ***does*** support scoped modules.

So I guess I wait until then. :frowning:

Thanks for the help and the thread here, even if it didn't pan out in my case. Hopefully this can add to the explanation / story here.

**Comment by jefflembeck** [comment]
@manovotny that's really rough, sorry to hear that! In case you didn’t know, npm also has an enterprise product as well. Lemme know if you are interested at all and I'll forward you to some folks. Good luck!

**Comment by manovotny** [comment]
@jefflembeck : : 

As much as I'd love you take you up on that offer, corporate america, "the cloud is evil", need something to support Java / Maven too, etc.

I appreciate the offer though!

**Comment by scott-joe** [comment]
Having the same problem. It's been suggested that the @ in the name is causing an issue due to npm's stricter naming conventions. https://github.com/npm/npm/issues/7269#issuecomment-72773658

**Comment by gnestor** [comment]
Updating npm worked for me: `npm install -g npm`
