### ISSUE TITLE
Different directories for outputted files

### ISSUE THREAD

**Issue by philipisik** [filamentgroup/grunticon#282]
Hi grunticon team,

is it possible to set different directories for the outputted files in the grunt configuration? I want to save the scss files in my scss directory, the js file in my js directory an the png fallback files in my image directory.

Cheers Philip

**Comment by philipisik** [comment]
P. S.: The classes in the three css files need different prefixes, because they will be concatenate to one file.

**Comment by extractachris** [comment]
+1

**Comment by davetgreen** [comment]
I've just started integrating Grunticon with our development boilerplate, and this is the single main thing I'd love to see added. +1
