### ISSUE TITLE
Rendered output file "grunticon.loader.js" gets 25 errors running through grunt-contrib-jshint

### ISSUE THREAD

**Issue by peterdillon** [filamentgroup/grunticon#283]
All are either "missing semicolon" or "Expected an assignment or function call and instead saw an expression."

Is there a way to do a "$ grunt --force" for this single file or do you have another solution?

**Comment by fingermaster** [comment]
We could use the jshint negate:

```jshint: {
  options: {
    smarttabs: true,
  },
  all: [
    '!js/grunticon-load.js',
  ],
},
```

**Comment by fingermaster** [comment]
We could use the jshint negate:

```jshint: {
options: {
smarttabs: true,
},
all: [
'!js/grunticon-load.js',
],
},```
