### ISSUE TITLE
Generated PNGs and PNG data-uris display SVG code not the rendered SVG

### ISSUE THREAD

**Issue by philsforcedgithubnameforwork** [filamentgroup/grunticon#285]
Windows 7 64bit.

Tried running grunticon and the images and data-uris that were created did not display the correct rendered SVGs and instead created images of the literal SVG code.

![text-motorcycle](https://cloud.githubusercontent.com/assets/12258758/9198775/6a511d80-400c-11e5-870e-15577283c81d.png)

**Comment by jefflembeck** [comment]
@philsforcedgithubnameforwork are you running this through some type of svg minifier first?

If it's svgmin, `removeXMLProcInst:false` is an option you'll want to use. If not, Windows has a fun rendering issue with SVGs where unless they start with `<?xml version="1.0" encoding="utf-8"?>`, they render as the test.

**Comment by philsforcedgithubnameforwork** [comment]
Yeah, it was the fun Windows issue. I added the xml encoding and the images were generated correctly. Thanks for the quick response and solution!
