### ISSUE TITLE
disable file creation

### ISSUE THREAD

**Issue by parkersweb** [filamentgroup/grunticon#286]
Hey there,

I'm using grunticon in a pretty simple case - so I'd like to produce just the datasvgcss file and the datapngcss file i.e. don't render the urlpngcss file, the png images or the preview file. 

I might be looking in the wrong place - but I can't find an option to turn them off - and setting the file name to "" doesn't work. Is it possible?

Thanks!

Andrew

**Comment by BrandonLive** [comment]
Did you find an answer for this?

**Comment by jefflembeck** [comment]
@BrandonLive this module is what we use to do it - https://github.com/filamentgroup/directory-encoder

**Comment by BrandonLive** [comment]
Yeah I found this Grunt task built on it which works well enough so far, though I may need to add some options to it and fix its glob handling if I get a chance.

https://www.npmjs.com/package/grunt-svg-css

Still feel like it would be an improvement to grunticon to have options for disabling different unneeded outputs, though.

**Comment by jefflembeck** [comment]
@BrandonLive Ah. We decided a while back that it's just not in the scope of the project. Grunticon is trying to solve a pretty specific problem and uses a few modules, pieced together, to do that.

Using `directory-encoder`, or even wrapping it as a grunt/gulp task is the popular choice we recommend.

Thanks
