### ISSUE TITLE
Embedded SVG not showing

### ISSUE THREAD

**Issue by peterdillon** [filamentgroup/grunticon#288]
Here is the error in chrome:
![screenshot 2015-08-15 18 30 52](https://cloud.githubusercontent.com/assets/307229/9291094/defde402-437b-11e5-8bfb-eee70dbe0ce5.png)

**Comment by benjgorman** [comment]
Are you using the correct callback? Have you defined your "enhanceSVG: true" in your grunt file options?

**Comment by fingermaster** [comment]
This is the preview page after running - the gruntfile is as follows:
```
   // SVG and fallback build - Grunticon
    grunticon: {
      projectIcons: {
        files: [{
            expand: true,
            cwd: 'icons/svg',
            src: ['*.svg', '*.png'],
            dest: "build/svg"
        }],
        options: {
          enhanceSVG: true
        }
      }
    },
```

**Comment by hitchmough** [comment]
I'm having the same issue - the SVG's appear fine but as soon as I add data-grunticon-embed the icons disappear. 

Same thing happens on the preview file that's generated by Grunt too.
