### ISSUE TITLE
Optimized URL encoding

### ISSUE THREAD

**Issue by strarsis** [filamentgroup/grunticon#296]
I don't know whether this has been already discussed here, 
I found no issues regarding this, so I create a new one.

Relating to this article and post (credits to them):
https://codepen.io/Tigt/blog/optimizing-svgs-in-data-uris
https://codepen.io/Tigt/blog/optimizing-svgs-in-data-uris#comment-id-2068

I ported this to a node module that encodes a text file (SVG file) string by this optimized way: 
https://github.com/strarsis/inline-urlescape

Maybe this could be used for encoding the SVGs in grunticon for inline usage?

**Comment by mwld** [comment]
I think base64 encoding is not being used anymore since version 0.1.6: https://github.com/filamentgroup/grunticon/blob/master/README.md#release-history
