### ISSUE TITLE
Dynamic colors not working; files are generated, but icon remains the original color

### ISSUE THREAD

**Issue by bendrexl** [filamentgroup/grunticon#298]
Pretty simple setup:

![image](https://cloud.githubusercontent.com/assets/5415207/10176752/5f8bb2d2-66ab-11e5-898d-dc623338b621.png)

![image](https://cloud.githubusercontent.com/assets/5415207/10176731/49dda38c-66ab-11e5-881c-64dd352a2bb7.png)

The files are generated as expected, but the color is always the original color.  If I drop the same SVG file on Grumpicon, things work as expected:

![image](https://cloud.githubusercontent.com/assets/5415207/10176806/b693b14c-66ab-11e5-9214-34223063190a.png)

I've spent the morning re-installing node packages & grunt modules, but nothing has changed... any ideas?

![image](https://cloud.githubusercontent.com/assets/5415207/10177043/df9d87e2-66ac-11e5-814f-025170ad5c2b.png)

**Comment by bendrexl** [comment]
I tried this with a fresh, bare-bones project on a different mac, same result - all generated icons are named correctly for each color, but none are actually colored.

**Comment by niorad** [comment]
It may have to do with the way your svgs are being exported.
Since the latest CC-Update, I need to modify the SVGs which Illustrator is generating (remove the color from the CSS and add it as attribute on the tag)
