### ISSUE TITLE
Errors installing grunticon

### ISSUE THREAD

**Issue by rachaedwards** [filamentgroup/grunticon#301]
Hi,  I'm having trouble installing this package.  I'll include what I saw in the command window below. Let me know if you'd also like to see the npm-debug file.

I've tried installing grunticon with the lines "npm install grunt-grunticon --save-dev", "npm install grunt-grunticon", and by adding the package as a dependency to the package.json file and running the line "npm install". 

Our other web designer also tried to install the package and got errors. Please let me know if you have any ideas about what's going wrong.

<h4>Error Message in Console</h4>

<pre><code class="markdown">

C:\Users\J1082\Desktop\grunt test project>npm install grunt-grunticon
npm WARN package.json my-project-name@0.1.0 No description
npm WARN package.json my-project-name@0.1.0 No repository field.
npm WARN package.json my-project-name@0.1.0 No README data
\
> phantomjs@1.9.18 install C:\Users\J1082\Desktop\grunt test project\node_module
s\grunt-grunticon\node_modules\grunticon-lib\node_modules\svg-to-png\node_module
s\phantomjs
> node install.js

Download already available at C:\Users\J1082\AppData\Local\Temp\phantomjs\phanto
mjs-1.9.8-windows.zip
Extracting zip contents
Removing C:\Users\J1082\Desktop\grunt test project\node_modules\grunt-grunticon\
node_modules\grunticon-lib\node_modules\svg-to-png\node_modules\phantomjs\lib\ph
antom
Copying extracted folder C:\Users\J1082\AppData\Local\Temp\phantomjs\phantomjs-1
.9.8-windows.zip-extract-1445896052595\phantomjs-1.9.8-windows -> C:\Users\J1082
\Desktop\grunt test project\node_modules\grunt-grunticon\node_modules\grunticon-
lib\node_modules\svg-to-png\node_modules\phantomjs\lib\phantom
Writing location.js file
Done. Phantomjs binary available at C:\Users\J1082\Desktop\grunt test project\no
de_modules\grunt-grunticon\node_modules\grunticon-lib\node_modules\svg-to-png\no
de_modules\phantomjs\lib\phantom\phantomjs.exe

> jpegtran-bin@3.0.5 postinstall C:\Users\J1082\Desktop\grunt test project\node_
modules\grunt-grunticon\node_modules\grunticon-lib\node_modules\svg-to-png\node_
modules\imagemin\node_modules\imagemin-jpegtran\node_modules\jpegtran-bin
> node lib/install.js

  v jpegtran pre-build test passed successfully

> gifsicle@3.0.1 postinstall C:\Users\J1082\Desktop\grunt test project\node_modu
les\grunt-grunticon\node_modules\grunticon-lib\node_modules\svg-to-png\node_modu
les\imagemin\node_modules\imagemin-gifsicle\node_modules\gifsicle
> node lib/install.js

  v gifsicle pre-build test passed successfully

> pngquant-bin@3.0.0 postinstall C:\Users\J1082\Desktop\grunt test project\node_
modules\grunt-grunticon\node_modules\grunticon-lib\node_modules\svg-to-png\node_
modules\imagemin\node_modules\imagemin-pngquant\node_modules\pngquant-bin
> node lib/install.js

  v pngquant pre-build test passed successfully

> optipng-bin@3.0.2 postinstall C:\Users\J1082\Desktop\grunt test project\node_m
odules\grunt-grunticon\node_modules\grunticon-lib\node_modules\svg-to-png\node_m
odules\imagemin\node_modules\imagemin-optipng\node_modules\optipng-bin
> node lib/install.js

  ? Command failed: C:\Windows\system32\cmd.exe /s /c "C:\Users\J1082\Desktop\gr
unt test project\node_modules\grunt-grunticon\node_modules\grunticon-lib\node_mo
dules\svg-to-png\node_modules\imagemin\node_modules\imagemin-optipng\node_module
s\optipng-bin\vendor\optipng.exe --version"
'C:\Users\J1082\Desktop\grunt' is not recognized as an internal or external comm
and,
operable program or batch file.

  ? optipng pre-build test failed
  i compiling from source
  x Error: ./configure --with-system-zlib --prefix="C:\Users\J1082\Desktop\grunt
 test project\node_modules\grunt-grunticon\node_modules\grunticon-lib\node_modul
es\svg-to-png\node_modules\imagemin\node_modules\imagemin-optipng\node_modules\o
ptipng-bin\vendor" --bindir="C:\Users\J1082\Desktop\grunt test project\node_modu
les\grunt-grunticon\node_modules\grunticon-lib\node_modules\svg-to-png\node_modu
les\imagemin\node_modules\imagemin-optipng\node_modules\optipng-bin\vendor" && m
ake install
Command failed: C:\Windows\system32\cmd.exe /s /c "./configure --with-system-zli
b --prefix="C:\Users\J1082\Desktop\grunt test project\node_modules\grunt-gruntic
on\node_modules\grunticon-lib\node_modules\svg-to-png\node_modules\imagemin\node
_modules\imagemin-optipng\node_modules\optipng-bin\vendor" --bindir="C:\Users\J1
082\Desktop\grunt test project\node_modules\grunt-grunticon\node_modules\gruntic
on-lib\node_modules\svg-to-png\node_modules\imagemin\node_modules\imagemin-optip
ng\node_modules\optipng-bin\vendor""
'.' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:751:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "grunt-grunticon"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! Invalid name: "@filamentgroup/worker-farm"
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
</code></pre>

**Comment by jefflembeck** [comment]
@rachaedwards what happens when you run `npm install @filamentgroup/worker-farm`?

**Comment by dmonin** [comment]
I have the same problem here:
```
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! Invalid name: "@filamentgroup/worker-farm"
npm ERR! 
```
@jefflembeck the same output, can't find worker-farm. Could it be issue with npm?

**Comment by adamlc** [comment]
I also got this error, the package does exist so I guess its an NPM issue?

https://www.npmjs.com/package/@filamentgroup/worker-farm

**Comment by adamlc** [comment]
I actually figured this out, because we're using a different NPM registry / proxy this broke. Changing the main registry back to NPM worked :)

**Comment by dmonin** [comment]
@adamlc How did you change it?

**Comment by adamlc** [comment]
Checkout your ~/.npmrc file. Chances are you'll have a custom registry set

**Comment by dmonin** [comment]
@adamlc, thank you for the info. Though, seems in my case it's something else. 

It seems I don't have this file (it's not in my ~ user directory).
```
$ npm config get registry
https://registry.npmjs.org/
```

**Comment by adamlc** [comment]
Fair enough, that looks totally normal. Removing my custom registry worked in my case. How strange :(

**Comment by samholguin** [comment]
I'm receiving the same errors as @rachaedwards and @dmonin in OSX El Capitan.

My registry is set to `registry = "https://registry.npmjs.org/"`

I don't have the user config file `.npmrc`

Any ideas how to fix this?

**Comment by johnhunter** [comment]
I have the same problem installing on Windows.

`npm ERR! Invalid name: "@filamentgroup/worker-farm"`

Also tried installing directly from the github repo with same results so its not a problem with the npm registry

```
  ...
  "grunt-grunticon": "git+https://github.com/filamentgroup/grunticon.git#2.2.0"
}
```

**Comment by samholguin** [comment]
@johnhunter I resolved my issue by updating both node and npm to the latest release

**Comment by jefflembeck** [comment]
@johnhunter Doing what @samholguin suggested should work. You probably don't need to even upgrade your node, but if you run `npm install -g npm@latest` (for npm 3) or `npm install -g npm@latest-2` (for npm 2). This should work nicely for you.

Thanks!

**Comment by johnhunter** [comment]
Thanks guys! I've got to resolve some other project dependency issues before I upgrade node. Have reverted to grunticon 2.1.6 for the moment.

**Comment by dmonin** [comment]
This time upgrading to newest version worked for me as well. Problem solved. Thanks everyone for help! :)

**Comment by Heidiworld** [comment]
I am also having problems installing "grunt-grunticon": "^2.2.2", on my mac. I'm running El Capitan. I've got node v2.4.4 and npm v3.5.3 but still get the error: 
npm ERR! fetch failed https://registry.npmjs.org/@filamentgroup/worker-farm/-/worker-farm-1.2.0.tgz

Please can you help? Thanks in advance

**Comment by bmatzner** [comment]
@Heidiworld same here

**Comment by dmonin** [comment]
hey guys,
have you tried installing latest nodejs (5.x) + npm (3.x)? 
Make sure to install it fresh and remove the old one. It worked for me.

**Comment by Heidiworld** [comment]
Hi Dmonin thanks for the suggestion. I went ahead and gave it a go. Sadly it didn't resolve the problem :(

**Comment by Heidiworld** [comment]
Seem my problem was an npm permissions issue. Same is this: https://github.com/filamentgroup/grunticon/issues/308#issuecomment-173513790.
All installation issues have now been resolved.

**Comment by jefflembeck** [comment]
@Heidiworld that's awesome. I'm glad that helped clear it up for you.

**Comment by scott-joe** [comment]
Having the same problem. It's been suggested that the @ in the name is causing an issue due to npm's stricter naming conventions. https://github.com/npm/npm/issues/7269#issuecomment-72773658

**Comment by jshemas** [comment]
I'm running `Node v5.8.0` and `NPM v3.7.3`, on `Mac 10.11.3` and keep getting the same error.

Also my registry is pointing to `https://registry.npmjs.org/`

**Comment by marcelkobainGIT** [comment]
I had the problem in npm on 2.15.1 and it is ok on npm 2.15.2.
