### ISSUE TITLE
Run grunticon in a folder that has only png will throw exception

### ISSUE THREAD

**Issue by nghiado** [filamentgroup/grunticon#311]
[INFO] Running "grunticon:commonIcons" (grunticon) task
[ERROR] Error: Input must be Array of SVG files or String that is a directory that contains some of those
[ERROR]     at Object.exports.convert (<MY_FOLDER>/node_modules/grunt-grunticon/node_modules/grunticon-lib/node_modules/svg-to-png/lib/svg-to-png.js:128:10)
[ERROR]     at null.<anonymous> (<MY_FOLDER>/node_modules/grunt-grunticon/node_modules/grunticon-lib/lib/grunticon-lib.js:206:13)
[ERROR]     at $$$internal$$tryCatch (<MY_FOLDER>/node_modules/grunt-grunticon/node_modules/grunticon-lib/node_modules/directory-colorfy/node_modules/rsvp/dist/rsvp.js:490:16)
[ERROR]     at $$$internal$$invokeCallback (<MY_FOLDER>/node_modules/grunt-grunticon/node_modules/grunticon-lib/node_modules/directory-colorfy/node_modules/rsvp/dist/rsvp.js:502:17)
[ERROR]     at <MY_FOLDER>/node_modules/grunt-grunticon/node_modules/grunticon-lib/node_modules/directory-colorfy/node_modules/rsvp/dist/rsvp.js:992:13
[ERROR]     at $$rsvp$asap$$flush (<MY_FOLDER>/node_modules/grunt-grunticon/node_modules/grunticon-lib/node_modules/directory-colorfy/node_modules/rsvp/dist/rsvp.js:1476:9)
[ERROR]     at nextTickCallbackWith0Args (node.js:415:9)
[ERROR]     at process._tickCallback (node.js:344:13)

**Comment by andrewcuthill** [comment]
It looks like this was fixed in filamentgroup/grunticon-lib#11
