### ISSUE TITLE
SVG inlining build process

### ISSUE THREAD

**Issue by JeroenReumkens** [filamentgroup/grunticon#312]
Hi Filament group,

It's great that grunticon now also supports the inlining of SVG's. Especially after reading this Github article I'm convinced to try it; https://github.com/blog/2112-delivering-octicons-with-svg.
However, if I'm correct you guys have implemented it so that it inserts the SVG's during runtime. Would it be possible to include this inserting / replacing in the build process for static pages? This would be great since it would be less HTTP requests. 

Looking forward to your answer,
Thanks,

Jeroen.

**Comment by dominikwilkowski** [comment]
Hey @JeroenReumkens,

Sorry to butch in here. Your idea of inserting SVGs in a compile phase is great. I might just try that for our codebase. However the way grunticon works it only requires ONE HTTP request as all svg icons are embedded inside one CSS file. I also wouldn't worry too much about HTTP requests anymore as HTTP/2 is now easily available and should probably get rid of this anti-pattern.

**Comment by JeroenReumkens** [comment]
Hi @dominikwilkowski,

You're right that the HTTP requests isn't the biggest problem. But still I think it would be great if we're able to insert a SVG icon with only one HTML-attribute or something like that. This would mean that we don't need any extra stylesheets or  javascript in order to render the icons, which is less to worry about. I like to keep solutions as simple as possible, and the thing Github came op with, is just that!

Of course that would also mean that you can not have a png fallback for other browsers. But if you look at the SVG support, this might nog even be necessary anymore.

**Comment by dominikwilkowski** [comment]
The problem with that is that each use of an SVG is another instance of it. If you were to add three instances of your "star" svg onto a page it will triple your code as you copy the SVG code three times into your HTML. Not a big problem with gzip but something to keep in mind. Grunticon gets them all from one SVG file be default with the drawback of it being a background image. If you embed your icon you will have the same issue. Have you had a look at [Chris Coyiers method](https://css-tricks.com/svg-sprites-use-better-icon-fonts/) to using SVGs? If you don't need IE8 support than this might be the better solution for you. Grunticon is a solution for all browsers.

**Comment by JeroenReumkens** [comment]
You're right that in the case you're using multiple instances of the same icon on one page, they will be transferred over the line in your HTML page and will be some extra data. Compared to Chris Coyiers method, that might seem a little bit less optimized. If the combined SVG is however pretty large, you might still transfer more data then the multiple star-icons that are gzipped. 

I do think both are great options, so I will evaluate both of them to see what suits me best. Thanks for thinking along with me! :)
