### ISSUE TITLE
svg.min.css file has media query "only x"

### ISSUE THREAD

**Issue by MickeyKay** [filamentgroup/grunticon#314]
Hi there,

It looks like I'm encountering some buggy behavior when trying to use the standard `grunticon()` call in my JS, without setting the `enhanceSVG` option to true in the Grunt build task.

_The Problem_
The link to the svg stylesheet that's autogenerated from the loader js looks like this:
`<link rel="stylesheet" href="{my_path}/icons.data.svg.css" media="only x">`

As you can see, the media type is set to `only x` which means the css isn't applied at all. This happens when I _don't_ set the `enhanceSVG` option to true in my Grunt task, and use the following initialization call:
`grunticon(["icons.data.svg.css", "icons.data.png.css", "icons.fallback.css"]);`

If, however, I set `enhanceSVG` to true - even if I don't actually use any embeddable SVG's, then this fixes the above problem.

So it seems like there may be an issue that arose when y'all added the new embeddable functionality that perhaps broke some backwards compatibility for setups in which `enhanceSVG` is false.

**Comment by dominikwilkowski** [comment]
Might have something to do with the path `{my_path}` see #234.
