### ISSUE TITLE
Please update your package references from phantomjs to phantomjs-prebuilt

### ISSUE THREAD

**Issue by andalusi** [filamentgroup/grunticon#315]
My site is broken due to this issue. Please update the references or at least give me a work arround.

**Comment by jefflembeck** [comment]
Working on this in svg-to-png, and a few others. I strongly encourage pull requests in those cases if it's immediately necessary as this project is totally powered by free time.

**Comment by andalusi** [comment]
I understand! So my workaround is to downgrade to npm 2.x

PS: Would love to help, unfortunately I'm not to deep into development ...

**Comment by andalusi** [comment]
@jefflembeck Is there a chance to use grunticon without svg-to-png?

Any help is much appreciated.

**Comment by gabrieledarrigo** [comment]
ps: Any chance to upgrade even `grunt`, since 1.0 is out?

**Comment by jefflembeck** [comment]
@gabrieledarrigo we can certainly do that. The other stuff is a bit slower. There are broken tests abound, unfortunately.

**Comment by gabrieledarrigo** [comment]
Yeah I know, transistion path to phantomjs 2 is not so easy : )

**Comment by therealpecus** [comment]
here's the relevant patch if you hit 

> PHANTOM ERROR: TypeError: undefined is not an object (evaluating 'phantom.args[0]')

modify phantomscript.js in /svg-to-png/lib/ on line 46 so that it reads:

```
	var options = (typeof(phantom.args) === "undefined") ? {
		inputFiles: JSON.parse(system.args[1]),
		dest: system.args[2],
		defaultWidth: system.args[3],
		defaultHeight: system.args[4]
	} : {
		inputFiles: JSON.parse(phantom.args[0]),
		dest: phantom.args[1],
		defaultWidth: phantom.args[2],
		defaultHeight: phantom.args[3]
	};
```

this should ensure backward compatibility with phantom 1.x and allow phantom 2 to ingest arguments correctly.
Tested with phantom-prebuilt 2.1.1 (installed with node) on Mac Os X 10.11.5.

**Comment by gabrieledarrigo** [comment]
Great! Did you open a PR?

**Comment by Aminta** [comment]
@therealpecus fantastic, you saved my workflow, thanks!

**Comment by lquintela** [comment]
@therealpecus really great fix!
