### ISSUE TITLE
Blurry Icons in IE 10 / 11

### ISSUE THREAD

**Issue by jesspritchard** [filamentgroup/grunticon#319]
Hi All,

I am having a slight problem with SVG icons looking blurry in IE 10 and 11 - see below for an example.

It uses the same data uri as chrome and they both decode to the same SVG code as well.

![blurry-icons](https://cloud.githubusercontent.com/assets/2003040/15139028/f1505b92-16d6-11e6-91ab-0810b08696cd.png)

Can anyone shed some light on why they might be blurry only in IE?

Thanks,
Jess

**Comment by emilbjorklund** [comment]
Hi @jesspritchard, this is not a bug specific to Grunticon, but rather a bug/quirk in IE with regards to rounding SVG background size values. See this post for more: https://thatemil.com/blog/2015/03/16/ie-blurry-svg-backgrounds-and-size-rounding/
