### ISSUE TITLE
CSS Dimensions from SVG Viewport

### ISSUE THREAD

**Issue by Mr-Chilly** [filamentgroup/grunticon#320]
Not sure if this is a thing - but is it possible to automatically set the generated CSS classes to have a height and width the same as the original SVGs (Viewport?)

Would be awesome to not have to set the dimensions manually, and I can't set a default as all of our SVGs are different sizes!

Good work all round by the way...

**Comment by jefflembeck** [comment]
This is definitely on my checklist of to-dos.

And thanks!
