### ISSUE TITLE
phantomjs Fatal error: Command failed

### ISSUE THREAD

**Issue by vorbe** [filamentgroup/grunticon#325]
I'm getting a fatal error when trying to run grunticon, any ideas as to what is causing this fatal error: command failed message ? I've tried this in a non spaced path and I still get the same issue.

Running "grunticon:myicons" (grunticon) task
svg-to-png now spawning phantomjs...
(using path: /Users/username/Google Drive/root/svg-test/node_modules/svg-to-png/node_modules/phantomjs/lib/phantom/bin/phantomjs)

Something went wrong with phantomjs...
Fatal error: Command failed: /Users/username/Google Drive/root/svg-test/node_modules/svg-to-png/node_modules/phantomjs/lib/phantom/bin/phantomjs /Users/okconsumer/Google Drive/root/svg-test/node_modules/svg-to-png/lib/phantomscript.js ["/var/folders/_h/wrzxm_j93yb_mpss9g93db4h0000gn/T/grunticon-tmp/bars.svg"] grunt/output/png 400px 300px

----
grunt file:

```
module.exports = function(grunt){
  grunt.initConfig({
    pkg: grunt.file.readJSON('package.json'),
    grunticon: {
      myicons: {
        files: [{
          expand: true,
          cwd: 'grunt/svgs',
          src: ['*.svg'],
          dest: 'grunt/output'
        }],
        options: {
          enhanceSVG: true
        }
      }
    }  
  });

  grunt.loadNpmTasks('grunt-grunticon');

  grunt.registerTask('default', ['grunticon']);
};
```

package.json 

`{
  "name": "icons",
  "version": "0.1.0",
  "devDependencies": {
    "grunt": "^0.4.5",
    "grunt-grunticon": "^2.2.3"
  }
}
`

**Comment by chillybin** [comment]
I have the same issue

```
Running "grunticon:build" (grunticon) task
svg-to-png now spawning phantomjs...
(using path: /node_modules/svg-to-png/node_modules/phantomjs/lib/phantom/bin/phantomjs)

Something went wrong with phantomjs...
Fatal error: Command failed: /node_modules/svg-to-png/node_modules/phantomjs/lib/phantom/bin/phantomjs /node_modules/svg-to-png/lib/phantomscript.js

Process finished with exit code 1
```

**Comment by aarfing** [comment]
Me too. Might be related to me just updating to MacOS Sierra GM, but not sure...

**Comment by webflo** [comment]
I have the same issue on Sierra. The same version works well on Linux.

**Comment by aarfing** [comment]
I've been playing around with permissions, but without luck so far. See https://github.com/filamentgroup/grunticon/issues/130

**Comment by aarfing** [comment]
Ok, so updating svg-to-png inside grunticon from version 2 to version 3 seems to make things work again. I haven't tested it heavily, but seems fine so far.

**Comment by paulstraw** [comment]
Can confirm, @aarfing's suggestion to update the `svg-to-png` dependency in `grunticon-lib` worked for me as well on Sierra GM.

**Comment by vorbe** [comment]
Thanks Paul,
 
I ran a new local install of grunt/ grunticon with the same gruntfile and package in my original comment  and updated svg-to-png to v3 in the package.json for grunticon-lib and it seems to work as expected now.

**Comment by mrmartineau** [comment]
For those interested, I am seeing this on my Windows build machine as well..

**Comment by jefflembeck** [comment]
@mrmartineau are you seeing this issue with the latest grunticon (2.3.0)?

**Comment by mrmartineau** [comment]
Yes I am, I figured out that the issue is with svg-to-png and logged an issue there, https://github.com/filamentgroup/svg-to-png/issues/19. Any help would be much appreciated.
