### ISSUE TITLE
Fails to install - phantomjs problem?

### ISSUE THREAD

**Issue by gvinson** [filamentgroup/grunticon#334]
Please include the following information with your issue:

I am trying to install 'grunt-grunticon: "^2.2.2" and today I started getting the following error:

sudo npm install grunt-grunticon --save-dev
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated node-uuid@1.4.7: use uuid module instead

> phantomjs-prebuilt@2.1.7 install /www/bankonit/node_modules/phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1//phantomjs-2.1.1-macosx.zip
Saving to /www/bankonit/node_modules/phantomjs-prebuilt/phantomjs/phantomjs-2.1.1-macosx.zip
Receiving...

Error making request.
Error: connect ETIMEDOUT 54.231.120.123:443
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)

Please report this full log at https://github.com/Medium/phantomjs
/www/bankonit
`-- (empty)

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "grunt-grunticon" "--save-dev"
npm ERR! node v5.1.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE

npm ERR! phantomjs-prebuilt@2.1.7 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs-prebuilt@2.1.7 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the phantomjs-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /www/bankonit/npm-debug.log
npm ERR! code 1

I am running OSX 10.10.5
node version = v5.1.0
npm version = 3.3.12

Has anyone else ran into this issue? Is there help out there?

**Comment by Pizdetss** [comment]
Install phantomjs separately and add it to path, have you tried that?

**Comment by Soben** [comment]
Also encountered this. Seems that the Google Code repository has been deprecated. Code needs to be updated to pull from an alternative source.
