### ISSUE TITLE
Running two sets of stylesheets on one page

### ISSUE THREAD

**Issue by spenno** [filamentgroup/grunticon#339]
Is it possible to run two sets of stylesheets on one page? I.e. two different SVG stylesheets, two different PNG stylesheets and two different fallback stylesheets.

I work for a large institution that will have 'global' styles and icons covering all websites. There will also be project specific styles and icons that are custom for individual websites.

It would be great to be able to use Grunticon for both global and project specific icons. Is this possible? I'm presuming a change to the Grunticon loader will be required?

**Comment by tommcc** [comment]
I was in a similar situation with a client and would have liked some features in Grunticon to handle individual "sets" of icons.

In the end we ended up combining the files in our build system instead. This had the added benefit of fewer external files loaded in the browser.
