### ISSUE TITLE
Grunticon stuck on 'grunticon now spawning phantomjs...'

### ISSUE THREAD

**Issue by matt-bailey** [filamentgroup/grunticon#40]
I guess this is probably not an issue with Grunticon per say, but when I run 'grunt' my grunticon task gets stuck on the message 'grunticon now spawning phantomjs...'.

The weird thing is that everything was working fine yesterday and I haven't touched the Gruntfile.js.

I have had other problems that seem to be related to phantomjs as well (I've disabled mocha as this also errors in the build process - something to do with phantomjs), but I can't seem to find any solution and as I said, grunticon was working perfectly yesterday (and on other older projects).

Any suggestions?

I'm on Mac OS X 10.8.3.

**Comment by Kurtmcmurt** [comment]
The reason this is occuring is due to local npm dependencies - I had this issue, but simply did npm install grunt-grunticon --save-dev and it worked
